### To do list :
- [ ] Continue the mass balance
- [ ] Manually check each reaction of exchange to find the problem
- [ ] Manually add fatty acid reaction with the help of biomass composition

### Setting up

In [ ]:
%pip install cobra

In [1]:
import cobra
import pandas as pd
from cobra.io import load_model
from cobra.io import load_json_model, save_json_model, load_matlab_model, save_matlab_model, read_sbml_model, write_sbml_model
from cobra import Model, Reaction, Metabolite

Upload model

In [49]:
model = read_sbml_model('C:\\Users\\benammara\\Documents\\PhD\\Data\\Models\\Manual Curation\\curated_grampos_4.sbml')

In [9]:
model1 = read_sbml_model('C:\\Users\\benammara\\Documents\\PhD\\Data\\Models\\Solarfood_original.sbml')

In [50]:
copy_of_model = model.copy()
copy_of_model

In [52]:
# set exchange reactions bounds to zero if they significally affect the growth
ex_list = []

not_to_change_list = ['EX_bz_e','EX_ca2_e','EX_cl_e','EX_cobalt2_e','EX_cu2_e','EX_inost_e','EX_h2s_e','EX_h2o_e','EX_h2o2_e','EX_h2_e'
                      ,'EX_glyc2p_e','EX_glyb_e','EX_glcur_e','EX_k_e','EX_mg2_e','EX_mn2_e','EX_salchs4fe_e','EX_zn2_e','EX_salchs4_e']
for element in copy_of_model.exchanges:
    reaction = copy_of_model.reactions.get_by_id(element.id)
    
    # Iterate over metabolites associated with the reaction
    for metabolite, coefficient in reaction.metabolites.items():
        if element.id not in not_to_change_list:
            # Set reaction bounds to zero
            reaction.bounds = 0.0, 0.0
            
            # Optimize the model
            solution = copy_of_model.slim_optimize()
            
            # Check if the solution is not zero
            if solution != 0.0:
                ex_list.append(reaction.id)
                
            # Print reaction information
            print(reaction.name)
            print(solution)

Could not identify an external compartment by name and choosing one with the most boundary reactions. That might be complete nonsense or change suddenly. Consider renaming your compartments using `Model.compartments` to fix this.
c:\Users\benammara\AppData\Local\Programs\Python\Python312\Lib\site-packages\cobra\medium\boundary_types.py:97: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  return most[0]

EX_12ppd__S_e
33.80064513854854
EX_25dkglcn_e
33.80064513854871
EX_2ameph_e
33.80064513854871
EX_2m35mdntha_e
33.80064513854871
EX_2pglyc_e
33.80064513854871
EX_34dhbz_e
33.80064513854871
EX_35dnta_e
33.80064513854871
EX_3gmp_e
33.80064513854871
EX_3h4atb_e
33.80064513854871
EX_4hba_e
33.79854338502087
EX_4hoxpac_e
33.798543385020956
EX_4hphac_e
33.798543385020956
EX_4hpro_DC_e
33.798543385020956
EX_4hpro_LT_e
33.798543385020956
EX_4oxptn_e
33.798543385020956
EX_5dglcn_e
33.79854338502093
EX_5drib_e
33.79854338502077
EX_5mcsn_e
33.79854338502077
EX_6atha_e
33.79854338502077
EX_LalaDgluMdapDala_e
33.79283264241994
EX_Lcyst_e
33.79283264241992
EX_R_3hhdca_e
28.94288963836226
EX_R_3hhpa_e
28.942889638362395
EX_R_3hnonaa_e
28.942889638362395
EX_R_3hpdeca_e
28.942889638362395
EX_R_3hphpa_e
28.942889638362395
EX_R_3hpnona_e
28.942889638362395
EX_R_3hpocta_e
28.942889638362395
EX_R_3htd58e_e
28.942889638362395
EX_abt__L_e
28.942889638362395
EX_ac_e
28.942889638362395
EX_acald_e
28.942889638362395
EX_acgam_e
28.942889638362395
EX_acmana_e
28.942889638362395
EX_acnam_e
28.894051042259974
EX_actn__R_e
28.89405104226002
EX_ade_e
28.79207582185872
EX_agm_e
28.79207582185854
EX_ala__D_e
28.79207582185854
EX_ala__L_e
28.79207582185854
EX_alahis_e
28.79207582185854
EX_alaleu_e
28.79207582185854
EX_alathr_e
28.79207582185854
EX_alatrp_e
28.79207582185854
EX_anhgm_e
28.79207582185854
EX_apc_e
28.79207582185854
EX_arab__L_e
28.79207582185854
EX_arbt6p_e
28.79207582185854
EX_arbt_e
28.79207582185854
EX_arg__L_e
28.35736763445048
EX_ascb__L_e
28.357367634450668
EX_asn__L_e
28.318652155853325
EX_asp__L_e
28.318652155853194
EX_buts_e
28.318652155853194
EX_carn_e
28.318652155853194
EX_cd2_e
28.318652155853194
EX_cellb_e
28.318652155853194
EX_cgly_e
28.318652155853243
EX_chol_e
28.318652155853243
EX_chols_e
28.318652155853243
EX_chtbs_e
28.318652155853243
EX_cinnm_e
28.318652155853243
EX_cit_e
28.318652155853243
EX_cm_e
28.318652155853243
EX_co2_e
16.773889843584218
EX_co_e
16.77388984358421
EX_crn_e
16.77388984358421
EX_csn_e
16.589785728650167
EX_cyan_e
16.58978572865021
EX_cys__L_e
16.58978572865021
EX_dca_e
16.58978572865021
EX_ddca_e
16.58978572865021
EX_dextrin_e
16.58978572865021
EX_drib_e
16.58978572865021
EX_dxyl_e
16.589724354596378
EX_enter_e
16.589724354596303
EX_fald_e
16.5897243545963
EX_fe2_e
16.58972435459634
EX_fe3_e
16.58972435459634
EX_fe3dcit_e
16.589724354596342
EX_fe3pyovd_kt_e
16.581734195033075
EX_feenter_e
16.58173419503303
EX_for_e
16.58139697092204
EX_frmd_e
16.581396970922096
EX_fru_e
16.41167770830293
EX_fuc_e
16.411677708302914
EX_g3pe_e
16.411677708302914
EX_g3pg_e
16.317673541853157
EX_gal_bD_e
16.317673541853168
EX_gal_e
16.317673541853168
EX_galt_e
16.317673541853168
EX_galur_e
16.317673541853168
EX_gam_e
16.298259215710846
EX_glc__D_e
16.29825921571085
EX_glc__aD_e
16.29825921571085
EX_gln__L_e
16.29825921571085
EX_glu__L_e
16.29825921571085
EX_gly_e
16.29825921571085
EX_glyc3p_e
15.933629704747306
EX_glyclt_e
15.933629704747265
EX_glygln_e
15.933629704747265
EX_glyglu_e
15.933629704747265
EX_glygly_e
15.933629704747265
EX_glymet_e
15.933629704747265
EX_glyphe_e
15.933629704747265
EX_glyser_e
15.933629704747265
EX_gthrd_e
15.933629704747265
EX_gua_e
15.87211723684746
EX_h_e
15.87211723684746
EX_hco3_e
15.872117236847375
EX_hdca_e
15.872117236847375
EX_hdcea_e
15.872117236847375
EX_hexs_e
15.872117236847375
EX_his__L_e
15.872117236847375
EX_hisgly_e
15.872117236847375
EX_hishis_e
15.758101736482933
EX_hpta_e
15.758101736482985
EX_hxa_e
15.758101736482985
EX_hxan_e
15.022537988255554
EX_icit_e
15.022537988255547
EX_id3acald_e
15.0225379882556
EX_ile__L_e
15.014067803051812
EX_ind3ac_e
15.014067803051796
EX_indole_e
15.004463693533804
EX_lcts_e
15.004463693534111
EX_leu__D_e
15.004463693534111
EX_leu__L_e
15.004463693534111
EX_leuleu_e
15.004463693534111
EX_lnlc_e
15.004463693534111
EX_lys__D_e
14.995671349508525
EX_lys__L_e
14.957187033942798
EX_m_xyl_e
14.957187033942875
EX_malt_e
14.7619648075149
EX_malthp_e
14.761964807514723
EX_malthx_e
14.761964807514723
EX_malttr_e
14.761964807514723
EX_maltttr_e
14.614307205564035
EX_man_e
14.614307205564035
EX_melib_e
14.614307205564035
EX_met__D_e
14.614307205564035
EX_met__L_e
14.614307205564035
EX_metox__R_e
14.614307205564035
EX_metox_e
14.581509404216984
EX_mnl_e
14.58150940421704
EX_mobd_e
14.58150940421704
EX_mso3_e
14.58150940421704
EX_na1_e
14.58150940421704
EX_nh4_e
14.487651836867348
EX_nmn_e
14.32945977468375
EX_no2_e
14.315920699119431
EX_no3_e
14.315920699119337
EX_no_e
13.464822773489576
EX_nona_e
13.464822773489429
EX_novbcn_e
13.464822773489429
EX_o2_e
13.409308871864086
EX_ocdca_e
13.409308871864457
EX_ocdcea_e
13.409308871864457
EX_octa_e
13.409308871864457
EX_orn__D_e
13.409308871864457
EX_orn_e
13.185470102728807
EX_p_xyl_e
13.185470102728472
EX_pdima_e
13.185470102728472
EX_pea_e
13.185470102728472
EX_peamn_e
13.185470102728472
EX_pentso3_e
13.185470102728472
EX_phe__L_e
13.017171426066964
EX_phedca_e
13.01717142606706
EX_phehpa_e
13.01717142606706
EX_phehxa_e
13.01717142606706
EX_pheme_e
13.01717142606706
EX_phenona_e
13.01717142606706
EX_pheocta_e
13.01717142606706
EX_phept_e
13.01717142606706
EX_pi_e
13.01717142606706
EX_pro__L_e
12.738283610393198
EX_progly_e
12.715404836260708
EX_pta_e
12.715404836260799
EX_ptrc_e
11.122562395687666
EX_ptsla_e
11.122562395688705
EX_pydxn_e
11.122297714181563
EX_pyovd_kt_e
11.1222977141815
EX_raffin_e
11.1222977141815
EX_rib__D_e
11.1222977141815
EX_rmn_e
11.1222977141815
EX_rnam_e
11.1222977141815
EX_s_e
11.119744760763822
EX_sbt__D_e
11.01866126819909
EX_sel_e
11.018661268198993
EX_ser__L_e
11.018661268198993
EX_sheme_e
11.018661268198993
EX_slnt_e
11.018661268198993
EX_so3_e
11.018661268198993
EX_so4_e
11.018483447706487
EX_spmd_e
11.010037656299264
EX_sucr_e
11.010037656299176
EX_tartr__D_e
11.010037656298978
EX_taur_e
11.010037656298978
EX_tcynt_e
11.010037656298978
EX_tet_e
11.010037656298978
EX_thr__L_e
11.010037656298978
EX_tnt_e
11.010037656298978
EX_tol_e
11.010037656298978
EX_tre_e
10.940487464410436
EX_trp__L_e
10.856244243919848
EX_tsul_e
10.85624424391977
EX_ttdca_e
10.85624424391977
EX_ttdcea_e
10.85624424391977
EX_ttrcyc_e
10.85624424391977
EX_tyr__D_e
10.842789132869688
EX_tyr__L_e
10.715228213853608
EX_urate_e
10.715228213853708
EX_urea_e
8.305525262910411
EX_vacc_e
8.305525262910402
EX_val__D_e
8.305525262910402
EX_val__L_e
7.767582308456841
EX_vanln_e
7.7675823084567375
EX_xyl__D_e
7.7675823084567375

In [35]:
# change bounds of the exchange reactions
for element in ex_list:
    reaction = copy_of_model.reactions.get_by_id(element)
    for metabolite, coefficient in reaction.metabolites.items():
        print(reaction.name)
        print(metabolite.name)
        print(metabolite.formula)
        reaction.bounds = -1000.0 , 1000.0

EX_12ppd__S_e
(S)-Propane-1,2-diol
C3H8O2
EX_25dkglcn_e
2,5-diketo-D-gluconate
C6H7O7
EX_2ameph_e
2-Aminoethylphosphonate
C2H7NO3P
EX_2m35mdntha_e
N  2 methyl 3 5 dinitrophenyl  4 methyl 3 5 dinitroaniline
HN
EX_2pglyc_e
2-Phosphoglycolate
C2H2O6P
EX_34dhbz_e
3,4-Dihydroxybenzoate
C7H5O4
EX_35dnta_e
N N bis 3 5 dinitrotolyl  amine
HN
EX_3gmp_e
Guanosine 3  phosphate C10H12N5O8P
C10H12N5O8P
EX_3h4atb_e
3 Hydroxy 4 acetylthiobutanoic acid
C6H9O4S
EX_4hba_e
4-Hydroxy-benzyl alcohol
C7H8O2
EX_4hoxpac_e
4 Hydroxyphenylacetic acid C8H8O3
C8H7O3
EX_4hphac_e
4-Hydroxyphenylacetate
C8H7O3
EX_4hpro_DC_e
Cis 4 Hydroxy D proline
C5H9NO3
EX_4hpro_LT_e
Trans 4 Hydroxy L proline C5H9NO3
C5H9NO3
EX_4oxptn_e
4 Oxopentanoate
C5H7O3
EX_5dglcn_e
5-Dehydro-D-gluconate
C6H9O7
EX_5drib_e
5'-deoxyribose
C5H10O4
EX_5mcsn_e
5-Methylcytosine
C5H7N3O
EX_6atha_e
6 acetylthiohexanoic acid
C8H13O3S
EX_LalaDgluMdapDala_e
L-alanine-D-glutamate-meso-2,6-diaminoheptanedioate-D-alanine
C18H30N5O9
EX_Lcyst_e
L-Cysteate
C3H6NO5S
EX_R_3hhdca_e
 3 Hydroxyhexadecanoic acid
C16H31O3
EX_R_3hhpa_e
 3 hydroxyheptanoic acid
C7H13O3
EX_R_3hnonaa_e
 3 hydroxynonanoic acid
C9H17O3
EX_R_3hpdeca_e
 3 Hydroxy 10 phenyldecanoic acid
C16H23O3
EX_R_3hphpa_e
 3 Hydroxy 7 phenylheptanoic acid
C13H17O3
EX_R_3hpnona_e
 3 Hydroxy 9 phenylnonanoic acid
C15H21O3
EX_R_3hpocta_e
 3 Hydroxy 8 phenyloctanoic acid
C14H19O3
EX_R_3htd58e_e
 3 hydroxy  5Z 8Z  tetradecedienic acid
C14H23O3
EX_abt__L_e
L Arabinitol C5H12O5
C5H12O5
EX_ac_e
Acetate
C2H3O2
EX_acald_e
Acetaldehyde
C2H4O
EX_acgam_e
N-Acetyl-D-glucosamine
C8H15NO6
EX_acmana_e
N-Acetyl-D-mannosamine
C8H15NO6
EX_acnam_e
N-Acetylneuraminate
C11H18NO9
EX_actn__R_e
 R  Acetoin C4H8O2
C4H8O2
EX_ade_e
Adenine
C5H5N5
EX_agm_e
Agmatine
C5H16N4
EX_ala__D_e
D-Alanine
C3H7NO2
EX_ala__L_e
L-Alanine
C3H7NO2
EX_alahis_e
L alaninylhistidine
C9H14N4O3
EX_alaleu_e
L alaninylleucine
C9H18N2O3
EX_alathr_e
L alaninylthreonine
C7H14N2O4
EX_alatrp_e
L alaninyltryptophan
C14H17N3O3
EX_anhgm_e
N-Acetyl-D-glucosamine(anhydrous)N-Acetylmuramic acid
C19H29N2O12
EX_apc_e
Ampicillin
C16H19N3O4S
EX_arab__L_e
L-Arabinose
C5H10O5
EX_arbt6p_e
Arbutin 6-phosphate
C12H15O10P
EX_arbt_e
Arbutin C12H16O7
C12H16O7
EX_arg__L_e
L-Arginine
C6H15N4O2
EX_ascb__L_e
L-Ascorbate
C6H8O6
EX_asn__L_e
L-Asparagine
C4H8N2O3
EX_asp__L_e
L-Aspartate
C4H6NO4
EX_buts_e
Butanesulfonate C4H9O3S
C4H9O3S
EX_carn_e
L-Carnosine
C9H14N4O3
EX_cd2_e
Cadmium
Cd
EX_cellb_e
Cellobiose
C12H22O11
EX_cgly_e
Cys Gly C5H10N2O3S
C5H10N2O3S
EX_chol_e
Choline C5H14NO
C5H14NO
EX_chols_e
Choline sulfate
C5H13NO4S
EX_chtbs_e
N,N'-diacetylchitobiose
C16H28N2O11
EX_cinnm_e
Trans-Cinnamate
C9H7O2
EX_cit_e
Citrate
C6H5O7
EX_cm_e
Chloramphenicol
C11H12Cl2N2O5
EX_co2_e
CO2 CO2
CO2
EX_co_e
Carbon monoxide
CO
EX_crn_e
L-Carnitine
C7H15NO3
EX_csn_e
Cytosine
C4H5N3O
EX_cyan_e
Hydrogen cyanide
CHN
EX_cys__L_e
L-Cysteine
C3H7NO2S
EX_dca_e
Decanoate (n-C10:0)
C10H19O2
EX_ddca_e
Dodecanoate (n-C12:0)
C12H23O2
EX_dextrin_e
Dextrin C12H20O10
C12H20O10
EX_drib_e
Deoxyribose C5H10O4
C5H10O4
EX_dxyl_e
1-deoxy-D-xylulose
C5H10O4
EX_enter_e
Enterochelin
C30H26N3O15
EX_fald_e
Formaldehyde
CH2O
EX_fe2_e
Fe2+ mitochondria
Fe
EX_fe3_e
Iron (Fe3+)
Fe
EX_fe3dcit_e
Fe(III)dicitrate
C12FeH10O14
EX_fe3pyovd_kt_e
Ferrypyoverdine  P putida KT2440 specific
C27FeH48N10O15
EX_feenter_e
Fe-enterobactin
C30FeH26N3O15
EX_for_e
Formate
CHO2
EX_frmd_e
Formamide
CH3NO
EX_fru_e
D-Fructose
C6H12O6
EX_fuc_e
L-fuculose
C6H12O5
EX_g3pe_e
Sn-Glycero-3-phosphoethanolamine
C5H14NO6P
EX_g3pg_e
Glycerophosphoglycerol
C6H14O8P
EX_gal_bD_e
Beta D-Galactose
C6H12O6
EX_gal_e
D-Galactose
C6H12O6
EX_galt_e
Galactitol
C6H14O6
EX_galur_e
D-Galacturonate
C6H9O7
EX_gam_e
D-Glucosamine
C6H14NO5
EX_glc__D_e
D-Glucose
C6H12O6
EX_glc__aD_e
Alpha D-glucose
C6H12O6
EX_gln__L_e
L-Glutamine
C5H10N2O3
EX_glu__L_e
L-Glutamate
C5H8NO4
EX_gly_e
Glycine
C2H5NO2
EX_glyc3p_e
Glycerol 3-phosphate
C3H7O6P
EX_glyclt_e
Glycolate C2H3O3
C2H3O3
EX_glygln_e
L glycinylglutamine
C7H13N3O4
EX_glyglu_e
L glycinylglutamate
C7H11N2O5
EX_glygly_e
Glycylglycine C4H8N2O3
C4H8N2O3
EX_glymet_e
L Glycinylmethionine
C7H14N2O3S
EX_glyphe_e
Glycylphenylalanine
C11H14N2O3
EX_glyser_e
L glycinylserine
C5H10N2O4
EX_gthrd_e
Reduced glutathione
C10H16N3O6S
EX_gua_e
Guanine
C5H5N5O
EX_h_e
H+
H
EX_hco3_e
Bicarbonate
CHO3
EX_hdca_e
Hexadecanoate (n-C16:0)
C16H31O2
EX_hdcea_e
Hexadecenoate (n-C16:1)
C16H29O2
EX_hexs_e
Hexanesulfonate C6H13O3S
C6H13O3S
EX_his__L_e
L-Histidine
C6H9N3O2
EX_hisgly_e
L histidinylglycine
C8H12N4O3
EX_hishis_e
L histidinylhistidine
C12H16N6O3
EX_hpta_e
Heptanoate
C7H13O2
EX_hxa_e
Hexanoate (n-C6:0)
C6H11O2
EX_hxan_e
Hypoxanthine
C5H4N4O
EX_icit_e
Isocitrate
C6H5O7
EX_id3acald_e
Indole 3 acetaldehyde C10H9NO
C10H9NO
EX_ile__L_e
L-Isoleucine
C6H13NO2
EX_ind3ac_e
Indole 3 acetate C10H8NO2
C10H8NO2
EX_indole_e
Indole
C8H7N
EX_lcts_e
Lactose C12H22O11
C12H22O11
EX_leu__D_e
D Leucine
C6H13NO2
EX_leu__L_e
L-Leucine
C6H13NO2
EX_leuleu_e
Leucylleucine
C12H24N2O3
EX_lnlc_e
Linoleic acid (all cis C18:2) n-6
C18H31O2
EX_lys__D_e
D-Lysine
C6H15N2O2
EX_lys__L_e
L-Lysine
C6H15N2O2
EX_m_xyl_e
M-Xylene
C8H10
EX_malt_e
Maltose C12H22O11
C12H22O11
EX_malthp_e
Maltoheptaose
C42H72O36
EX_malthx_e
Maltohexaose
C36H62O31
EX_malttr_e
Maltotriose C18H32O16
C18H32O16
EX_maltttr_e
Maltotetraose
C24H42O21
EX_man_e
D-Mannose
C6H12O6
EX_melib_e
Melibiose C12H22O11
C12H22O11
EX_met__D_e
D-Methionine
C5H11NO2S
EX_met__L_e
L-Methionine
C5H11NO2S
EX_metox__R_e
L methionine R oxide C5H11NO3S
C5H11NO3S
EX_metox_e
L Methionine S oxide C5H11NO3S
C5H11NO3S
EX_mnl_e
D-Mannitol
C6H14O6
EX_mobd_e
Molybdate
MoO4
EX_mso3_e
Methanesulfonate
CH3O3S
EX_na1_e
Sodium
Na
EX_nh4_e
Ammonium
H4N
EX_nmn_e
NMN C11H14N2O8P
C11H14N2O8P
EX_no2_e
Nitrite
NO2
EX_no3_e
Nitrate
NO3
EX_no_e
Nitric oxide
NO
EX_nona_e
Nonanoate C9H17O2
C9H17O2
EX_novbcn_e
Novobiocin
C31H35N2O11
EX_o2_e
O2 O2
O2
EX_ocdca_e
Octadecanoate (n-C18:0)
C18H35O2
EX_ocdcea_e
Octadecenoate (n-C18:1)
C18H33O2
EX_octa_e
Octanoate (n-C8:0)
C8H15O2
EX_orn__D_e
D-Ornithine
C5H13N2O2
EX_orn_e
Ornithine
C5H13N2O2
EX_p_xyl_e
P-methyltoluene
C8H10
EX_pdima_e
Phthiocerol dimycocerosate A (Mtb)
C96H190O5
EX_pea_e
Phenylethyl alcohol
C8H10O
EX_peamn_e
Phenethylamine
C8H12N
EX_pentso3_e
Pentanesulfonate
C5H11O3S
EX_phe__L_e
L-Phenylalanine
C9H11NO2
EX_phedca_e
10 Phenyldecanoic acid
C16H23O2
EX_phehpa_e
7 Phenylheptanoic acid
C13H17O2
EX_phehxa_e
6 Phenylhexanoic acid
C12H15O2
EX_pheme_e
Protoheme C34H30FeN4O4
C34H30FeN4O4
EX_phenona_e
9 Phenylnonanoic acid
C15H21O2
EX_pheocta_e
8 Phenyloctanoic acid
C14H19O2
EX_phept_e
5 phenylvaleric acid
C11H13O2
EX_pi_e
Phosphate
HO4P
EX_pro__L_e
L-Proline
C5H9NO2
EX_progly_e
L-Prolinylglycine
C7H12N2O3
EX_pta_e
Pentanoate
C5H9O2
EX_ptrc_e
Putrescine
C4H14N2
EX_ptsla_e
Petroselaidic acid
C18H33O2
EX_pydxn_e
Pyridoxine
C8H11NO3
EX_pyovd_kt_e
Pyoverdine  P putida specific
C27H48N10O15
EX_raffin_e
Raffinose C18H32O16
C18H32O16
EX_rib__D_e
D-Ribose
C5H10O5
EX_rmn_e
L-Rhamnose
C6H12O5
EX_rnam_e
N Ribosylnicotinamide C11H15N2O5
C11H15N2O5
EX_s_e
Sulfur
S
EX_sbt__D_e
D-Sorbitol
C6H14O6
EX_sel_e
Selenate
O4Se
EX_ser__L_e
L-Serine
C3H7NO3
EX_sheme_e
Siroheme C42H36FeN4O16
C42H36FeN4O16
EX_slnt_e
Selenite
O3Se
EX_so3_e
Sulfite
O3S
EX_so4_e
Sulfate
O4S
EX_spmd_e
Spermidine
C7H22N3
EX_sucr_e
Sucrose C12H22O11
C12H22O11
EX_tartr__D_e
D-tartrate
C4H4O6
EX_taur_e
Taurine C2H7NO3S
C2H7NO3S
EX_tcynt_e
Thiocyanate
CNS
EX_tet_e
Tetrathionate
O6S4
EX_thr__L_e
L-Threonine
C4H9NO3
EX_tnt_e
2 4 6 Trinitrotoluene
NO2
EX_tol_e
Toluene
C7H8
EX_tre_e
Trehalose
C12H22O11
EX_trp__L_e
L-Tryptophan
C11H12N2O2
EX_tsul_e
Thiosulfate
O3S2
EX_ttdca_e
Tetradecanoate (n-C14:0)
C14H27O2
EX_ttdcea_e
Tetradecenoate (n-C14:1)
C14H25O2
EX_ttrcyc_e
Tetracycline
C22H24N2O8
EX_tyr__D_e
D Tyrosine
C9H11NO3
EX_tyr__L_e
L-Tyrosine
C9H11NO3
EX_urate_e
Urate C5H4N4O3
C5H4N4O3
EX_urea_e
Urea CH4N2O
CH4N2O
EX_vacc_e
Vaccenic acid
C18H33O2
EX_val__D_e
D Valine
C5H11NO2
EX_val__L_e
L-Valine
C5H11NO2
EX_vanln_e
Vanillin
C8H8O3
EX_xyl__D_e
D-Xylose
C5H10O5

In [54]:
# set reactions bounds for a specific reaction 
reaction = copy_of_model.reactions.get_by_id('EX_glcur_e')
reaction.bounds = -10.0, 10.0

In [55]:
copy_of_model.summary()

In [16]:
model1.summary()

# Manual Curation

## Adding metabolites

In [20]:
new_metabolite = Metabolite(
    id='ethyln_c',     # Metabolite ID
    name='Ethylnitronate',     # Metabolite Name
    formula='C2H4NO2',         # Chemical Formula
    compartment='c'            # Compartment (e.g., cytoplasm)
)

new_metabolite.charge = -1   

copy_of_model.add_metabolites([new_metabolite])

print(new_metabolite.formula)

C2H4NO2

## Adding reactions

### Search metabolite

In [126]:
search_word = 'pro__L'
# Iterate over metabolites in the model
for metabolite in copy_of_model.metabolites:
    if search_word in metabolite.id:
        # Print metabolite information
        print(metabolite)
        print(metabolite.formula)
        print(metabolite.name)
        
        # Get related reactions
        related_reactions = list(metabolite.reactions)
        
        # Get genes related to the reactions
        related_genes = set()
        for reaction in related_reactions:
            related_genes.update(reaction.genes)
        
        # Print related reactions and associated genes
        print(f"Related Reactions: {', '.join(r.id for r in related_reactions)}")
        print(f"Genes Associated: {', '.join(g.id for g in related_genes)}\n")

pro__L_c
C5H9NO2
L-Proline
Related Reactions: P5CR, PROt2rpp, P5CRx, AMPTASEPG, PROR, PROabcpp, PROt2r, Growth, PROabc, ORNCD_1, 1P2CBXLR, PROD3, PROD2
Genes Associated: AAFOLC_16870, AAFOLC_21075, AAFOLC_06230, AAFOLC_11340, AAFOLC_05885, AAFOLC_12995, AAFOLC_05565, AAFOLC_05895, AAFOLC_05910, AAFOLC_05900, AAFOLC_00045, AAFOLC_13000, AAFOLC_12990, AAFOLC_12985, AAFOLC_08165, AAFOLC_22230, AAFOLC_11090, AAFOLC_16295, AAFOLC_18495, AAFOLC_16300

pro__L_e
C5H9NO2
L-Proline
Related Reactions: PROabc, PROtex, EX_pro__L_e, PROt2r
Genes Associated: AAFOLC_16870, AAFOLC_11340, AAFOLC_05565, AAFOLC_21075, AAFOLC_08165

pro__L_p
C5H9NO2
L-Proline
Related Reactions: PROt2rpp, PROtex, PROabcpp
Genes Associated: AAFOLC_16870, AAFOLC_13000, AAFOLC_12990, AAFOLC_21075, AAFOLC_12985, AAFOLC_05885, AAFOLC_11090, AAFOLC_12995, AAFOLC_05895, AAFOLC_05910, AAFOLC_05900

### Search reaction

In [ ]:
search_word = 'THZPSN'

for reaction in model.reactions:
    if search_word in reaction.id:
        print(f"Reaction ID: {reaction.id}")
        print(f"Name: {reaction.name}")
        print(f"Equation: {reaction.reaction}")
        print(f"Lower Bound: {reaction.lower_bound}")
        print(f"Upper Bound: {reaction.upper_bound}")
        print(f"Genes: {[gene.id for gene in reaction.genes]}")

### Check reaction

In [53]:

# Example reaction ID to check
reaction_id_to_check = 'Growth'

# Get the reaction
reaction = copy_of_model.reactions.get_by_id(reaction_id_to_check)

# Print information
print(f"Reaction ID: {reaction.id}")
print(f"Name: {reaction.name}")
print(f"Equation: {reaction.reaction}")
print(f"Lower Bound: {reaction.lower_bound}")
print(f"Upper Bound: {reaction.upper_bound}")

# Print metabolites and stoichiometry
print("\nMetabolites and Stoichiometry:")
for metabolite, coefficient in reaction.metabolites.items():
    print(f"{metabolite.id}: {coefficient} {metabolite.charge}")

# Print associated genes
print("\nAssociated Genes:")
for gene in reaction.genes:
    print(gene.id)

Reaction ID: Growth
Name: Biomass reaction
Equation: 0.000223 10fthf_c + 0.513689 ala__L_c + 0.000223 amet_c + 0.295792 arg__L_c + 0.241055 asn__L_c + 0.241055 asp__L_c + 54.124831 atp_c + 0.005205 ca2_c + 0.005205 cl_c + 0.000576 coa_c + 0.0001 cobalt2_c + 0.133508 ctp_c + 0.000709 cu2_c + 0.09158 cys__L_c + 0.026166 datp_c + 0.027017 dctp_c + 0.027017 dgtp_c + 0.026166 dttp_c + 0.000223 fad_c + 0.006715 fe2_c + 0.007808 fe3_c + 0.26316 gln__L_c + 0.26316 glu__L_c + 0.612638 gly_c + 0.001 gtca1_45_BS_c + 0.001 gtca2_45_BS_c + 0.001 gtca3_45_BS_c + 0.215096 gtp_c + 48.601527 h2o_c + 0.094738 his__L_c + 0.290529 ile__L_c + 0.195193 k_c + 0.450531 leu__L_c + 5e-05 lipo1_24_BS_c + 5e-05 lipo2_24_BS_c + 5e-05 lipo3_24_BS_c + 5e-05 lipo4_24_BS_c + 0.343161 lys__L_c + 0.153686 met__L_c + 0.008675 mg2_c + 0.000223 mlthf_c + 0.000691 mn2_c + 0.0001 mql8_c + 0.001831 nad_c + 0.000447 nadp_c + 0.01 peptido_BS_c + 0.185265 phe__L_c + 0.221055 pro__L_c + 0.000223 pydx5p_c + 0.000223 ribflv_c + 0.215792 ser__L_c + 0.004338 so4_c + 0.000223 thf_c + 0.000223 thmpp_c + 0.253687 thr__L_c + 0.056843 trp__L_c + 0.137896 tyr__L_c + 0.144104 utp_c + 0.423162 val__L_c + 0.000341 zn2_c --> 53.95 adp_c + 53.95 h_c + 53.945662 pi_c + 0.773903 ppi_c
Lower Bound: 0.0
Upper Bound: 1000.0

Metabolites and Stoichiometry:
10fthf_c: -0.000223 -2
ala__L_c: -0.513689 0
amet_c: -0.000223 1
arg__L_c: -0.295792 1
asn__L_c: -0.241055 0
asp__L_c: -0.241055 -1
atp_c: -54.124831 -4
ca2_c: -0.005205 2
cl_c: -0.005205 -1
coa_c: -0.000576 -4
cobalt2_c: -0.0001 2
ctp_c: -0.133508 -4
cu2_c: -0.000709 2
cys__L_c: -0.09158 0
datp_c: -0.026166 -4
dctp_c: -0.027017 -4
dgtp_c: -0.027017 -4
dttp_c: -0.026166 -4
fad_c: -0.000223 -2
fe2_c: -0.006715 2
fe3_c: -0.007808 3
gln__L_c: -0.26316 0
glu__L_c: -0.26316 -1
gly_c: -0.612638 0
gtca1_45_BS_c: -0.001 -45
gtca2_45_BS_c: -0.001 -45
gtca3_45_BS_c: -0.001 -45
gtp_c: -0.215096 -4
h2o_c: -48.601527 0
his__L_c: -0.094738 0
ile__L_c: -0.290529 0
k_c: -0.195193 1
leu__L_c: -0.450531 0
lipo1_24_BS_c: -5e-05 -2400
lipo2_24_BS_c: -5e-05 -2400
lipo3_24_BS_c: -5e-05 -2400
lipo4_24_BS_c: -5e-05 -2400
lys__L_c: -0.343161 1
met__L_c: -0.153686 0
mg2_c: -0.008675 2
mlthf_c: -0.000223 -2
mn2_c: -0.000691 2
mql8_c: -0.0001 0
nad_c: -0.001831 -1
nadp_c: -0.000447 -3
peptido_BS_c: -0.01 -2
phe__L_c: -0.185265 0
pro__L_c: -0.221055 0
pydx5p_c: -0.000223 -2
ribflv_c: -0.000223 0
ser__L_c: -0.215792 0
so4_c: -0.004338 -2
thf_c: -0.000223 -2
thmpp_c: -0.000223 -2
thr__L_c: -0.253687 0
trp__L_c: -0.056843 0
tyr__L_c: -0.137896 0
utp_c: -0.144104 -4
val__L_c: -0.423162 0
zn2_c: -0.000341 2
adp_c: 53.95 -3
h_c: 53.95 1
pi_c: 53.945662 -2
ppi_c: 0.773903 -3

Associated Genes:

<b>We found out that the model contains one reaction of three for the polyhydroxybutyrate which is 'Acetoacetyl CoA reductase' </b>

### Check gene

In [ ]:

# Example gene ID to check
gene_id_to_check = 'AAFOLC_08105'

# Get the gene
gene = model.genes.get_by_id(gene_id_to_check)

# Print information about the gene
print(f"Gene ID: {gene.id}")
print(f"Name: {gene.name}")

# Print reactions associated with the gene
print("\nReactions Associated with the Gene:")
for reaction in gene.reactions:
    print(f"Reaction ID: {reaction.id}")
    print(f"Name: {reaction.name}")
    print(f"Equation: {reaction.reaction}")
    print(f"Lower Bound: {reaction.lower_bound}")
    print(f"Upper Bound: {reaction.upper_bound}")

    # Print metabolites and stoichiometry
    print("\nMetabolites and Stoichiometry:")
    for metabolite, coefficient in reaction.metabolites.items():
        print(f"{metabolite.id}: {coefficient}")

## Mass and charge balance

### Read excel files

In [61]:
file_path = 'C:\\Users\\benammara\\Documents\\PhD\\Data\\Models\\Manual Curation\\Modified reactions.xlsx'
file_path_1 = 'C:\\Users\\benammara\\Documents\\PhD\\Data\\Models\\Manual Curation\\Modified formula.xlsx'
# Read Excel files into DataFrames
excel_data = pd.read_excel(file_path)
excel_data_formula = pd.read_excel(file_path_1)

### Check number of unbalanced reactions

In [47]:
print(len(cobra.manipulation.validate.check_mass_balance(copy_of_model)))
list_reactions = cobra.manipulation.validate.check_mass_balance(copy_of_model)
for reaction, balance_dict in list_reactions.items():
    reaction_id = reaction.id
    charge_balance = balance_dict
    print(f"Reaction ID: {reaction_id}, Charge Balance: {charge_balance}")

6
Reaction ID: G3POA_BS, Charge Balance: {'charge': 8.881784197001252e-16, 'C': -7.105427357601002e-15, 'N': -8.881784197001252e-16, 'O': -3.552713678800501e-15}
Reaction ID: HDECH, Charge Balance: {'charge': 2.0}
Reaction ID: MECDPDH4E, Charge Balance: {'charge': -1.0}
Reaction ID: P9DH, Charge Balance: {'charge': 4.0}
Reaction ID: THZSN_1, Charge Balance: {'charge': 1.0}
Reaction ID: VOR2bE, Charge Balance: {'charge': 1.0}

### Reaction information

In [63]:
reaction_id_to_check = 'Growth'
reaction = copy_of_model.reactions.get_by_id(reaction_id_to_check)
print(f"Reaction ID: {reaction.id}")
print(f"Name: {reaction.name}")
print(f"Equation: {reaction.reaction}")
print(f"Lower Bound: {reaction.lower_bound}")
print(f"Upper Bound: {reaction.upper_bound}")
sum = 0
#reaction.name = 'branched-chain ketoacid ferredoxin reductase'
print("\nMetabolites and Stoichiometry:")
for metabolite, coefficient in reaction.metabolites.items():
    print(f"{metabolite.id:<15}: {coefficient:>10}  Name: {metabolite.name:<60}  Charge: {metabolite.charge:>3}  Formula: {metabolite.formula}")
    sum += coefficient * metabolite.charge
print(f'\nSum charge: {sum}')
print("\nAssociated Genes:")
for gene in reaction.genes:
    print(gene.id)

Reaction ID: Growth
Name: Biomass equation measured by SolarFoods
Equation: 0.000223 10fthf_c + 0.000223 2dmmql8_c + 0.000223 5mthf_c + 0.000279 accoa_c + 0.816872 ala__L_c + 0.000223 amet_c + 0.255798 arg__L_c + 0.252959 asn__L_c + 0.252959 asp__L_c + 29.190682 atp_c + 0.004952 ca2_c + 0.000223 chor_c + 0.004952 cl_c + 0.002944 clpn160_p + 0.00229 clpn161_p + 0.00118 clpn181_p + 0.000168 coa_c + 2.4e-05 cobalt2_c + 0.010737 ctp_c + 0.006744 cu2_c + 0.037472 cys__L_c + 0.014833 datp_c + 0.015499 dctp_c + 0.024005 dgtp_c + 0.013367 dttp_c + 0.000223 enter_c + 0.000223 fad_c + 0.006388 fe2_c + 0.007428 fe3_c + 0.644556 fru_c + 0.005772 gal_c + 0.117367 glc__D_c + 0.275321 gln__L_c + 0.275321 glu__L_c + 0.637966 gly_c + 0.000223 gthrd_c + 0.01659 gtp_c + 29.180423 h2o_c + 0.000223 hemeO_c + 0.093522 his__L_c + 0.245064 ile__L_c + 0.18569 k_c + 0.480939 leu__L_c + 0.257602 lys__L_c + 3.1e-05 malcoa_c + 0.00481 man_c + 0.142675 met__L_c + 0.008253 mg2_c + 0.000223 mlthf_c + 0.000658 mn2_c + 7e-06 mobd_c + 0.000223 mql8_c + 0.000605 murein3px4p_p + 0.001345 murein4p3p_p + 0.005381 murein4p4p_p + 0.005448 murein4px4p_p + 0.000673 murein4px4px4p_p + 0.000502 nac_c + 0.001787 nad_c + 4.5e-05 nadh_c + 0.000112 nadp_c + 0.000335 nadph_c + 0.012379 nh4_c + 0.000307 ni2_c + 0.044164 pe160_p + 0.017704 pe181_p + 0.010599 pg160_p + 0.008244 pg161_p + 0.228463 phe__L_c + 0.000223 pheme_c + 8.6e-05 pnto__R_c + 0.289116 pro__L_c + 0.03327 ptrc_c + 0.000223 pydx5p_c + 6.4e-05 pydxn_c + 5.4e-05 rbflvrd_c + 0.000223 ribflv_c + 0.298559 ser__L_c + 0.000223 sheme_c + 0.004126 so4_c + 0.006744 spmd_c + 9.8e-05 succoa_c + 0.000223 thf_c + 1.3e-05 thm_c + 0.000223 thmpp_c + 0.330852 thr__L_c + 0.080977 trp__L_c + 0.159326 tyr__L_c + 0.006775 utp_c + 0.410868 val__L_c + 0.005772 xyl__D_c + 0.000324 zn2_c --> 29.180423 adp_c + 29.180423 h_c + 29.180423 pi_c + 0.110381 ppi_c
Lower Bound: 0.0
Upper Bound: 1000.0

Metabolites and Stoichiometry:
cu2_c          :  -0.006744  Name: Copper                                                        Charge:   2  Formula: Cu
h2o_c          : -29.180423  Name: H2O H2O                                                       Charge:   0  Formula: H2O
ca2_c          :  -0.004952  Name: Calcium                                                       Charge:   2  Formula: Ca
10fthf_c       :  -0.000223  Name: 10-Formyltetrahydrofolate                                     Charge:  -2  Formula: C20H21N7O7
pydx5p_c       :  -0.000223  Name: Pyridoxal 5'-phosphate                                        Charge:  -2  Formula: C8H8NO6P
murein3px4p_p  :  -0.000605  Name: Two disacharide linked murein units, tripeptide crosslinked tetrapeptide (A2pm->D-ala) (middle of chain)  Charge:  -4  Formula: C71H107N13O38
thr__L_c       :  -0.330852  Name: L-Threonine                                                   Charge:   0  Formula: C4H9NO3
gthrd_c        :  -0.000223  Name: Reduced glutathione                                           Charge:  -1  Formula: C10H16N3O6S
thmpp_c        :  -0.000223  Name: Thiamine diphosphate                                          Charge:  -2  Formula: C12H16N4O7P2S
ni2_c          :  -0.000307  Name: Nickel                                                        Charge:   2  Formula: Ni
mn2_c          :  -0.000658  Name: Manganese                                                     Charge:   2  Formula: Mn
sheme_c        :  -0.000223  Name: Siroheme C42H36FeN4O16                                        Charge:  -8  Formula: C42H36FeN4O16
ser__L_c       :  -0.298559  Name: L-Serine                                                      Charge:   0  Formula: C3H7NO3
ctp_c          :  -0.010737  Name: CTP C9H12N3O14P3                                              Charge:  -4  Formula: C9H12N3O14P3
accoa_c        :  -0.000279  Name: Acetyl-CoA                                                    Charge:  -4  Formula: C23H34N7O17P3S
arg__L_c       :  -0.255798  Name: L-Arginine                                                    Charge:   1  Formula: C6H15N4O2
asp__L_c       :  -0.252959  Name: L-Aspartate                                                   Charge:  -1  Formula: C4H6NO4
murein4p3p_p   :  -0.001345  Name: Two linked disacharide tetrapeptide and tripeptide murein units (uncrosslinked, middle of chain)  Charge:  -4  Formula: C71H109N13O39
5mthf_c        :  -0.000223  Name: 5-Methyltetrahydrofolate                                      Charge:  -1  Formula: C20H24N7O6
nad_c          :  -0.001787  Name: Nicotinamide adenine dinucleotide                             Charge:  -1  Formula: C21H26N7O14P2
mg2_c          :  -0.008253  Name: Magnesium                                                     Charge:   2  Formula: Mg
met__L_c       :  -0.142675  Name: L-Methionine                                                  Charge:   0  Formula: C5H11NO2S
nh4_c          :  -0.012379  Name: Ammonium                                                      Charge:   1  Formula: H4N
chor_c         :  -0.000223  Name: Chorismate                                                    Charge:  -2  Formula: C10H8O6
zn2_c          :  -0.000324  Name: Zinc                                                          Charge:   2  Formula: Zn
thf_c          :  -0.000223  Name: 5,6,7,8-Tetrahydrofolate                                      Charge:  -2  Formula: C19H21N7O6
dttp_c         :  -0.013367  Name: DTTP C10H13N2O14P3                                            Charge:  -4  Formula: C10H13N2O14P3
dctp_c         :  -0.015499  Name: DCTP C9H12N3O13P3                                             Charge:  -4  Formula: C9H12N3O13P3
cobalt2_c      :   -2.4e-05  Name: Co2+                                                          Charge:   2  Formula: Co
utp_c          :  -0.006775  Name: UTP C9H11N2O15P3                                              Charge:  -4  Formula: C9H11N2O15P3
k_c            :   -0.18569  Name: Potassium                                                     Charge:   1  Formula: K
fe2_c          :  -0.006388  Name: Fe2+                                                          Charge:   2  Formula: Fe
datp_c         :  -0.014833  Name: DATP C10H12N5O12P3                                            Charge:  -4  Formula: C10H12N5O12P3
nadp_c         :  -0.000112  Name: Nicotinamide adenine dinucleotide phosphate                   Charge:  -3  Formula: C21H25N7O17P3
glu__L_c       :  -0.275321  Name: L-Glutamate                                                   Charge:  -1  Formula: C5H8NO4
spmd_c         :  -0.006744  Name: Spermidine                                                    Charge:   3  Formula: C7H22N3
ile__L_c       :  -0.245064  Name: L-Isoleucine                                                  Charge:   0  Formula: C6H13NO2
hemeO_c        :  -0.000223  Name: Heme O C49H56FeN4O5                                           Charge:   0  Formula: C49FeH56N4O5
murein4p4p_p   :  -0.005381  Name: Two linked disacharide tetrapeptide murein units (uncrosslinked, middle of chain)  Charge:  -4  Formula: C74H114N14O40
gln__L_c       :  -0.275321  Name: L-Glutamine                                                   Charge:   0  Formula: C5H10N2O3
fe3_c          :  -0.007428  Name: Iron (Fe3+)                                                   Charge:   3  Formula: Fe
ala__L_c       :  -0.816872  Name: L-Alanine                                                     Charge:   0  Formula: C3H7NO2
phe__L_c       :  -0.228463  Name: L-Phenylalanine                                               Charge:   0  Formula: C9H11NO2
mlthf_c        :  -0.000223  Name: 5,10-Methylenetetrahydrofolate                                Charge:  -2  Formula: C20H21N7O6
2dmmql8_c      :  -0.000223  Name: 2-Demethylmenaquinol 8                                        Charge:   0  Formula: C50H72O2
gly_c          :  -0.637966  Name: Glycine                                                       Charge:   0  Formula: C2H5NO2
malcoa_c       :   -3.1e-05  Name: Malonyl CoA C24H33N7O19P3S                                    Charge:  -5  Formula: C24H33N7O19P3S
murein4px4p_p  :  -0.005448  Name: Two disacharide linked murein units, tetrapeptide corsslinked tetrapeptide (A2pm->D-ala) (middle of chain)  Charge:   0  Formula: C74H112N14O39
mql8_c         :  -0.000223  Name: Menaquinol 8                                                  Charge:   0  Formula: C51H74O2
cl_c           :  -0.004952  Name: Chloride                                                      Charge:  -1  Formula: Cl
his__L_c       :  -0.093522  Name: L-Histidine                                                   Charge:   0  Formula: C6H9N3O2
ribflv_c       :  -0.000223  Name: Riboflavin C17H20N4O6                                         Charge:   0  Formula: C17H22N4O6
so4_c          :  -0.004126  Name: Sulfate                                                       Charge:  -2  Formula: O4S
ptrc_c         :   -0.03327  Name: Putrescine                                                    Charge:   2  Formula: C4H14N2
gtp_c          :   -0.01659  Name: GTP C10H12N5O14P3                                             Charge:  -4  Formula: C10H12N5O14P3
pheme_c        :  -0.000223  Name: Protoheme C34H30FeN4O4                                        Charge:  -2  Formula: C34H30FeN4O4
nadph_c        :  -0.000335  Name: Nicotinamide adenine dinucleotide phosphate - reduced         Charge:  -4  Formula: C21H26N7O17P3
val__L_c       :  -0.410868  Name: L-Valine                                                      Charge:   0  Formula: C5H11NO2
pro__L_c       :  -0.289116  Name: L-Proline                                                     Charge:   0  Formula: C5H9NO2
mobd_c         :     -7e-06  Name: Molybdate                                                     Charge:  -2  Formula: MoO4
nadh_c         :   -4.5e-05  Name: Nicotinamide adenine dinucleotide - reduced                   Charge:  -2  Formula: C21H27N7O14P2
coa_c          :  -0.000168  Name: Coenzyme A                                                    Charge:  -4  Formula: C21H32N7O16P3S
asn__L_c       :  -0.252959  Name: L-Asparagine                                                  Charge:   0  Formula: C4H8N2O3
leu__L_c       :  -0.480939  Name: L-Leucine                                                     Charge:   0  Formula: C6H13NO2
enter_c        :  -0.000223  Name: Enterochelin                                                  Charge:  -1  Formula: C30H26N3O15
murein4px4px4p_p:  -0.000673  Name: Three disacharide linked murein units (tetrapeptide crosslinked tetrapeptide (A2pm->D-ala) & tetrapeptide corsslinked tetrapeptide (A2pm->D-ala)) (middle of chain)  Charge:  -6  Formula: C111H167N21O58
dgtp_c         :  -0.024005  Name: DGTP C10H12N5O13P3                                            Charge:  -4  Formula: C10H12N5O13P3
fad_c          :  -0.000223  Name: Flavin adenine dinucleotide oxidized                          Charge:   0  Formula: C27H33N9O15P2
succoa_c       :   -9.8e-05  Name: Succinyl-CoA                                                  Charge:  -5  Formula: C25H35N7O19P3S
thm_c          :   -1.3e-05  Name: Thiamin                                                       Charge:   1  Formula: C12H17N4OS
rbflvrd_c      :   -5.4e-05  Name: Reduced riboflavin                                            Charge:   0  Formula: C17H24N4O6
pydxn_c        :   -6.4e-05  Name: Pyridoxine                                                    Charge:   0  Formula: C8H11NO3
nac_c          :  -0.000502  Name: Nicotinate                                                    Charge:  -1  Formula: C6H4NO2
pnto__R_c      :   -8.6e-05  Name: (R)-Pantothenate                                              Charge:  -1  Formula: C9H16NO5
clpn161_p      :   -0.00229  Name: Cardiolipin (tetrahexadec-9-enoyl, n-C16:1)                   Charge:  -2  Formula: C73H132O17P2
pe160_p        :  -0.044164  Name: Phosphatidylethanolamine (dihexadecanoyl, n-C16:0)            Charge:   0  Formula: C37H74NO8P
pg160_p        :  -0.010599  Name: Phosphatidylglycerol (dihexadecanoyl, n-C16:0)                Charge:   0  Formula: C38H74O10P
clpn160_p      :  -0.002944  Name: Cardiolipin (tetrahexadecanoyl, n-C16:0)                      Charge:  -2  Formula: C73H140O17P2
clpn181_p      :   -0.00118  Name: Cardiolipin (tetraoctadec-11-enoyl, n-C18:1)                  Charge:  -2  Formula: C81H148O17P2
pe181_p        :  -0.017704  Name: Phosphatidylethanolamine (dioctadec-11-enoyl, n-C18:1)        Charge:   0  Formula: C41H78NO8P
pg161_p        :  -0.008244  Name: Phosphatidylglycerol (dihexadec-9-enoyl, n-C16:1)             Charge:  -1  Formula: C38H70O10P
tyr__L_c       :  -0.159326  Name: L-Tyrosine                                                    Charge:   0  Formula: C9H11NO3
cys__L_c       :  -0.037472  Name: L-Cysteine                                                    Charge:   0  Formula: C3H7NO2S
amet_c         :  -0.000223  Name: S-Adenosyl-L-methionine                                       Charge:   1  Formula: C15H23N6O5S
trp__L_c       :  -0.080977  Name: L-Tryptophan                                                  Charge:   0  Formula: C11H12N2O2
lys__L_c       :  -0.257602  Name: L-Lysine                                                      Charge:   1  Formula: C6H15N2O2
atp_c          : -29.190682  Name: ATP C10H12N5O13P3                                             Charge:  -4  Formula: C10H12N5O13P3
gal_c          :  -0.005772  Name: D-Galactose                                                   Charge:   0  Formula: C6H12O6
glc__D_c       :  -0.117367  Name: D-Glucose                                                     Charge:   0  Formula: C6H12O6
fru_c          :  -0.644556  Name: D-Fructose                                                    Charge:   0  Formula: C6H12O6
xyl__D_c       :  -0.005772  Name: D-Xylose                                                      Charge:   0  Formula: C5H10O5
man_c          :   -0.00481  Name: D-Mannose                                                     Charge:   0  Formula: C6H12O6
h_c            :  29.180423  Name: H+                                                            Charge:   1  Formula: H
pi_c           :  29.180423  Name: Phosphate                                                     Charge:  -2  Formula: HO4P
ppi_c          :   0.110381  Name: Diphosphate                                                   Charge:  -3  Formula: HO7P2
adp_c          :  29.180423  Name: ADP C10H12N5O10P2                                             Charge:  -3  Formula: C10H12N5O10P2

Sum charge: -0.1508630000000153

Associated Genes:

### Add metabolite

In [98]:
reaction = copy_of_model.reactions.get_by_id(reaction_id_to_check)
reaction.add_metabolites({"h_c": -1.0})
print(reaction.reaction)

gcvHL_nhLA_c + h_c + nad_c --> gcvHL_ADPr_c + ncam_c

### Remove metabolite

In [97]:
reaction = copy_of_model.reactions.get_by_id(reaction_id_to_check)
reaction.subtract_metabolites({"h_c": 1.0})
print(reaction.reaction)

gcvHL_nhLA_c + nad_c --> gcvHL_ADPr_c + ncam_c

### Change charge of metabolite

In [87]:
metabolite_id = 'gcvHL_ADPr_c'
if metabolite_id in model.metabolites:
    metabolite = copy_of_model.metabolites.get_by_id(metabolite_id)
    initial_charge = metabolite.charge  # Store the initial charge for reference
    metabolite.charge = -3
    print(list(metabolite.reactions))  
    # Print information about the modified metabolite
    print(f"Modified metabolite: {metabolite.id}")
    print(f"Updated charge: {metabolite.charge}")
else:
    print("Metabolite not found in the model.")

[<Reaction GCVHADPr at 0x29b62ca1280>, <Reaction GCVHRADPr at 0x29b62ca06b0>]
Modified metabolite: gcvHL_ADPr_c
Updated charge: -3

#### Add to excel file

In [36]:
# Create a dictionary containing information about the modified reaction
new_row = {'Reaction': reaction_id_to_check, 'metabolite changed': metabolite_id, 'initial charge': initial_charge, 'New charge': metabolite.charge}
excel_data = pd.concat([excel_data, pd.DataFrame([new_row])], ignore_index=True)
excel_data

        Reaction metabolite changed  initial charge  New charge
0    1P2CBXLCYCL          1p2cbxl_c               0          -1
1     2AGPGAT160           pg160_c                0          -1
2     3HAACOAT80        R_3hocoa_c                0          -4
3     3HAACOAT80              ACP_c               1          -1
4       2DGULRGx          2dhguln_c               0          -1
..           ...                ...             ...         ...
246       ACLS_b          hethmpp_c              -1          -1
247       APAT_1      hd_7_10_coa_c              -1          -3
248       ACLS_b          hethmpp_c              -2          -2
249      PREPTHS       prephthACP_c               0          -1
250    PREPHACPH          prephth_c               0          -1

[251 rows x 4 columns]

### Change formula of metabolite

In [108]:
metabolite_id = 'gcvHL_nhLA_c'
metabolite = copy_of_model.metabolites.get_by_id(metabolite_id)
initial_formula = metabolite.formula
metabolite.formula = 'C568H892N131O191P2S4'

#### Add to excel file

In [109]:
new_row_1 = {
    'Reaction': reaction_id_to_check,        # ID of the reaction associated with the metabolite change
    'metabolite changed': metabolite_id,     # ID of the metabolite that was changed
    'initial formula': initial_formula,      # Initial formula of the metabolite
    'New formula': metabolite.formula        # New formula of the metabolite after modification
}
excel_data_formula = pd.concat([excel_data_formula, pd.DataFrame([new_row_1])], ignore_index=False)

excel_data_formula = excel_data_formula.reset_index(drop=True)

excel_data_formula

     Reaction metabolite changed       initial formula           New formula
0     HACD31i        3ohd58coa_c        C35H50N7O18P3S        C35H52N7O18P3S
1    RECOAH24      R_3htd58coa_c        C35H52N7O18P3S        C35H54N7O18P3S
2  RHACOAE142        R_3htd58e_c              C14H21O3              C14H23O3
3   RHA142tpp        R_3htd58e_p              C14H21O3              C14H23O3
4   RHA142tex        R_3htd58e_e              C14H21O3              C14H23O3
5    GCVHADPr       gcvHL_nhLA_c  C568H892N131O191P2S4  C568H892N131O191P2S4

### Save updated files

#### Save Excel

In [60]:
# Save the updated DataFrame to the Excel file
excel_data.to_excel('C:\\Users\\benammara\\Documents\\PhD\\Data\\Models\\Manual Curation\\Modified reactions.xlsx', index=False)
excel_data_formula.to_excel('C:\\Users\\benammara\\Documents\\PhD\\Data\\Models\\Manual Curation\\Modified formula.xlsx', index=False)

#### Save model in SBML

In [56]:
sbml_filename = "C:\\Users\\benammara\\Documents\\PhD\\Data\\Models\\Manual Curation\\curated_grampos_updated_EX.sbml"
cobra.io.write_sbml_model(copy_of_model, sbml_filename)

# Update new model

### Update charges from excel

In [ ]:
file_path = 'Manual Curation\\Modified reactions.xlsx'
file_path_1 = 'Manual Curation\\Modified formula v2.xlsx'

excel_data_charge = pd.read_excel(file_path)

# Iterate over each component in the Excel file
for component in excel_data_charge['metabolite changed']:
    # Check if a metabolite is present in the model's metabolites
    metabolite_id = component
    if metabolite_id in copy_of_model.metabolites:
        # Get the metabolite from the model
        metabolite = copy_of_model.metabolites.get_by_id(metabolite_id)
        
        # Change the charge of the metabolite to a new value from the Excel file
        new_charge = int(excel_data_charge.loc[excel_data_charge['metabolite changed'] == metabolite_id, 'New charge'].values[0])
        metabolite.charge = new_charge
        
        # Print information about the modified metabolite
        print(f"Modified metabolite: {metabolite.id}")
        print(f"Updated charge: {metabolite.charge}")
    else:
        print("Metabolite not found in the model.")

### Create a list of reaction to update with the related model

In [ ]:
import requests
list_reactions = cobra.manipulation.validate.check_mass_balance(copy_of_model)

# Dictionary to store reaction ID and associated model
reaction_model_mapping = {}

for reaction, balance_dict in list_reactions.items():
    reaction_id = reaction.id  # Get the ID of the reaction
    # URL of the API endpoint for the reaction
    url = f'http://bigg.ucsd.edu/api/v2/universal/reactions/{reaction_id}'
    response = requests.get(url)
    if response.status_code == 200:
        data = response.json()
        # Extract the model ID from the JSON data
        model_of_reaction = data['models_containing_reaction'][0]['bigg_id']
        # Store the mapping of reaction ID to its model in the dictionary
        reaction_model_mapping[reaction_id] = model_of_reaction
    else:
        # If the request was not successful, print the status code
        print("Failed to retrieve data. Status code:", response.status_code)
print(reaction_model_mapping)

### Update charge from BIGG API

In [ ]:
for reaction, model_name in reaction_model_mapping.items():
    reaction_to_modify = copy_of_model.reactions.get_by_id(reaction)
    for metabolite, coefficient in reaction_to_modify.metabolites.items():
        if metabolite.charge == 0:
            url = f'http://bigg.ucsd.edu/api/v2/models/{model_name}/metabolites/{metabolite.id}'
            response = requests.get(url)
            if response.status_code == 200:
                data = response.json()
                # Check if the charge information is available and matches the current metabolite charge
                if data['charge'] is not None and data['charge'] == metabolite.charge:
                    print(metabolite.id)
                    metabolite.charge = data['charge']
            else:
                print("Failed to retrieve data. Status code:", response.status_code)

### Update metabolite with coa substring

In [ ]:
substring_to_check = 'coa'
for metabolite in copy_of_model.metabolites:
    if substring_to_check in metabolite.id:
        if metabolite.charge == 0:
            metabolite.charge = -4
            # Print information about the modified metabolite
            print(f"Modified metabolite: {metabolite.id}")
            print(f"Updated charge of : {metabolite.charge}")

I noticed that carveme doesn't provide the appropriate charge for metabolites with Coa molecules