In [ ]:
%pip install cobra

In [2]:
import cobra
import numpy as np
import pandas as pd
from cobra.io import load_model
from cobra.io import load_json_model, save_json_model, load_matlab_model, save_matlab_model, read_sbml_model, write_sbml_model
from cobra import Model, Reaction, Metabolite, Gene

In [6]:
model = read_sbml_model('C:\\Users\\adam-1y9pxi6q95ggpmx\\Documents\\PhD\\10-19 Research\\11 Data\\11.09 Models\\Manual_curation\\Energy_consumption\\250203_ETC_complex_IV_update.sbml')

## NGAM calculation

In [68]:
reaction = model.reactions.get_by_id('EX_co2_e')
reaction.bounds = -100.0, 0.0

reaction = model.reactions.get_by_id('EX_o2_e')
reaction.bounds = -100.0, 0.0

# set reactions bounds for a specific reaction 
reaction = model.reactions.get_by_id('EX_h2_e')
reaction.bounds = -15.27, -15.27

In [69]:
reaction = model.reactions.get_by_id('EX_h2_e')
reaction.bounds = -15.27, -15.27

In [13]:
model.objective = 'Growth'
solution = model.optimize()
print(f"Flux through ATPM: {solution.objective_value} mmol/gDW/hr")

Flux through ATPM: 0.06319004284167716 mmol/gDW/hr

GAM determination

In [12]:
reaction = model.reactions.get_by_id('ATPM')
reaction.bounds = 11.55, 1000.0

In [15]:
model.summary()

In [72]:
reaction = model.reactions.get_by_id('EX_co2_e')
reaction.bounds = -100.0, 0.0

reaction = model.reactions.get_by_id('EX_o2_e')
reaction.bounds = -100.0, 0.0

In [66]:
list_h2_fluxes=[18,19]
dict_slope={}

for gam in range(1,30):


    GAM_metabolites_1 = {'atp_c': -gam, 'h2o_c': -gam}
    GAM_metabolites_2 = {'adp_c': gam, 'pi_c': gam, 'h_c': gam}

    # Get the biomass reaction
    reaction = model.reactions.get_by_id('Growth')

    # Update the coefficients for GAM_metabolites_1
    for element, new_coefficient in GAM_metabolites_1.items():
        metabolite = model.metabolites.get_by_id(element)
        if metabolite in reaction.metabolites:
            reaction.add_metabolites({metabolite: new_coefficient - reaction.metabolites[metabolite]})
    
    

    # Update the coefficients for GAM_metabolites_2
    for element, new_coefficient in GAM_metabolites_2.items():
        metabolite = model.metabolites.get_by_id(element)
        if metabolite in reaction.metabolites:
            reaction.add_metabolites({metabolite: new_coefficient - reaction.metabolites[metabolite]})
    list_growth=[]

    # set reactions bounds for a specific reaction 
    for fluxe in list_h2_fluxes:
        reaction = model.reactions.get_by_id('EX_h2_e')
        reaction.bounds = -fluxe, 0.0
        model.objective = 'Growth'
        solution = model.slim_optimize()
        list_growth.append(solution)
        print(solution)
    
    dict_slope[gam]=(list_h2_fluxes[0]-list_h2_fluxes[1])/(list_growth[0]-list_growth[1])

print(dict_slope)

0.06914166192587129
0.07376137207682044
0.06892937277712688
0.07353489879787112
0.0687183832423727
0.07330981196681127
0.06850868142386493
0.07308609889093862
0.06830025556863437
0.07286374703202346
0.06809309406630788
0.07264274400392284
0.06788718544695646
0.07242307757036007
0.06768251837895006
0.07220473564258076
0.06747908166691849
0.07198770627718139
0.06727686424967555
0.07177197767392424
0.06707585519824819
0.0715575381736346
0.06687604371386337
0.07134437625599425
0.06667741912606337
0.0711324805376037
0.06647997089076073
0.07092183976987437
0.06628368858840475
0.07071244283707395
0.06608856192213651
0.07050427875435207
0.0658945807159913
0.07029733666583451
0.06570173491312248
0.07009160584273019
0.0655100145740695
0.06988707568146807
0.06531940987505554
0.06968373570189706
0.06512991110629392
0.06948157554546742
0.06494150867035617
0.06928058497349539
0.06475419308054252
0.06908075386543078
0.06456795495928316
0.06888207221714145
0.0643827850365908
0.06868453013925843
0.06419867414851523
0.06848811785554332
0.0640156132356171
0.06829282570124874
0.06383359334150923
0.06809864412156658
0.0636526056113653
0.06790556367002956
{1: 216.46379693205262, 2: 217.13046359868426, 3: 217.79713026521546, 4: 218.46379693204906, 5: 219.13046359844537, 6: 219.7971302654166, 7: 220.4637969321078, 8: 221.13046359854516, 9: 221.79713026534046, 10: 222.46379693236327, 11: 223.13046359861718, 12: 223.79713026531223, 13: 224.46379693209497, 14: 225.1304635988142, 15: 225.79713026535399, 16: 226.4637969319821, 17: 227.13046359874008, 18: 227.79713026536785, 19: 228.46379693207757, 20: 229.1304635987048, 21: 229.79713026538542, 22: 230.46379693220044, 23: 231.13046359888986, 24: 231.79713026540313, 25: 232.4637969320571, 26: 233.13046359870336, 27: 233.7971302653825, 28: 234.46379693199216, 29: 235.130463598805}

In [67]:
reaction_id_to_check = 'Growth'
reaction = model.reactions.get_by_id(reaction_id_to_check)
print(f"Reaction ID: {reaction.id}")
print(f"Name: {reaction.name}")
print(f"Equation: {reaction.reaction}")
print(f"Lower Bound: {reaction.lower_bound}")
print(f"Upper Bound: {reaction.upper_bound}")
sum = 0
#reaction.name = '(S)-2-Acetolactate pyruvate-lyase (carboxylating)'
print("\nMetabolites and Stoichiometry:")
for metabolite, coefficient in reaction.metabolites.items():
    print(f"{metabolite.id:<15}: {coefficient:>25}  Name: {metabolite.name:<60}  Charge: {metabolite.charge:>3}  Formula: {metabolite.formula}")
    sum += coefficient * metabolite.charge
print(f'\nSum charge: {sum}')
print("\nAssociated Genes:")
for gene in reaction.genes:
    print(gene.id)

Reaction ID: Growth
Name: Biomass reaction
Equation: 0.000223 10fthf_c + 0.000223 2dmmql8_c + 0.000223 5mthf_c + 0.000279 accoa_c + 0.513689 ala__L_c + 0.000223 amet_c + 0.030016 arab__L_c + 0.295792 arg__L_c + 0.241055 asn__L_c + 0.241055 asp__L_c + 29.0 atp_c + 0.005205 ca2_c + 0.000223 chor_c + 0.005205 cl_c + 0.002944 clpn160_p + 0.00229 clpn161_p + 0.00118 clpn181_p + 0.000576 coa_c + 0.0001 cobalt2_c + 0.133508 ctp_c + 0.000709 cu2_c + 0.09158 cys__L_c + 0.026166 datp_c + 0.027017 dctp_c + 0.027017 dgtp_c + 0.026166 dttp_c + 0.000223 fad_c + 0.006715 fe2_c + 0.007808 fe3_c + 0.644556 fru_c + 0.005772 gal_c + 0.117366841601577 glc__D_c + 0.26316 gln__L_c + 0.26316 glu__L_c + 0.612638 gly_c + 0.215096 gtp_c + 29.0 h2o_c + 0.000223 hemeO_c + 0.049935 hexadecacid_c + 0.007033 hexedecacid_c + 0.094738 his__L_c + 0.290529 ile__L_c + 0.195193 k_c + 0.019456 kdo2lipid4_p + 0.450531 leu__L_c + 0.005903 lnlc_c + 0.000364 lnlncg_c + 0.343161 lys__L_c + 3.1e-05 malcoa_c + 0.00481 man_c + 0.153686 met__L_c + 0.008675 mg2_c + 0.000223 mlthf_c + 0.000691 mn2_c + 7e-06 mobd_c + 0.0001 mql8_c + 0.000605 murein3px4p_p + 0.001345 murein4p3p_p + 0.005381 murein4p4p_p + 0.005448 murein4px4p_p + 0.000673 murein4px4px4p_p + 0.013894 murein5px4p_p + 0.000502314222072026 nac_c + 0.001831 nad_c + 4.5e-05 nadh_c + 0.000447 nadp_c + 0.000335 nadph_c + 0.012379 nh4_c + 0.007174 octadecacid_c + 0.131979 octedecacid_c + 0.017868 pe160_c + 0.045946 pe160_p + 0.054154 pe161_c + 0.02106 pe161_p + 0.017704 pe181_p + 0.010599 pg160_p + 0.008244 pg161_p + 0.185265 phe__L_c + 0.000223 pheme_c + 8.60937958309439e-05 pnto__R_c + 0.221055 pro__L_c + 0.03327 ptrc_c + 0.000223 pydx5p_c + 5.42885385395863e-05 rbflvrd_c + 0.000223 ribflv_c + 0.215792 ser__L_c + 0.000223 sheme_c + 0.004338 so4_c + 9.8e-05 succoa_c + 0.000223 thf_c + 1.3e-05 thm_c + 0.000223 thmpp_c + 0.253687 thr__L_c + 0.056843 trp__L_c + 0.000594246551765006 ttdca_c + 0.137896 tyr__L_c + 0.144104 utp_c + 0.423162 val__L_c + 0.005772 xyl__D_c + 0.000341 zn2_c --> 29.0 adp_c + 29.0 h_c + 29.0 pi_c + 0.773903 ppi_c
Lower Bound: 0.0
Upper Bound: 1000.0

Metabolites and Stoichiometry:
10fthf_c       :                 -0.000223  Name: 10-Formyltetrahydrofolate                                     Charge:  -2  Formula: C20H21N7O7
ala__L_c       :                 -0.513689  Name: L-Alanine                                                     Charge:   0  Formula: C3H7NO2
amet_c         :                 -0.000223  Name: S-Adenosyl-L-methionine                                       Charge:   1  Formula: C15H23N6O5S
arg__L_c       :                 -0.295792  Name: L-Arginine                                                    Charge:   1  Formula: C6H15N4O2
asn__L_c       :                 -0.241055  Name: L-Asparagine                                                  Charge:   0  Formula: C4H8N2O3
asp__L_c       :                 -0.241055  Name: L-Aspartate                                                   Charge:  -1  Formula: C4H6NO4
atp_c          :                     -29.0  Name: ATP C10H12N5O13P3                                             Charge:  -4  Formula: C10H12N5O13P3
ca2_c          :                 -0.005205  Name: Calcium                                                       Charge:   2  Formula: Ca
cl_c           :                 -0.005205  Name: Chloride                                                      Charge:  -1  Formula: Cl
coa_c          :                 -0.000576  Name: Coenzyme A                                                    Charge:  -4  Formula: C21H32N7O16P3S
cobalt2_c      :                   -0.0001  Name: Co2+                                                          Charge:   2  Formula: Co
ctp_c          :                 -0.133508  Name: CTP C9H12N3O14P3                                              Charge:  -4  Formula: C9H12N3O14P3
cu2_c          :                 -0.000709  Name: Copper                                                        Charge:   2  Formula: Cu
cys__L_c       :                  -0.09158  Name: L-Cysteine                                                    Charge:   0  Formula: C3H7NO2S
datp_c         :                 -0.026166  Name: DATP C10H12N5O12P3                                            Charge:  -4  Formula: C10H12N5O12P3
dctp_c         :                 -0.027017  Name: DCTP C9H12N3O13P3                                             Charge:  -4  Formula: C9H12N3O13P3
dgtp_c         :                 -0.027017  Name: DGTP C10H12N5O13P3                                            Charge:  -4  Formula: C10H12N5O13P3
dttp_c         :                 -0.026166  Name: DTTP C10H13N2O14P3                                            Charge:  -4  Formula: C10H13N2O14P3
fad_c          :                 -0.000223  Name: Flavin adenine dinucleotide oxidized                          Charge:  -2  Formula: C27H31N9O15P2
fe2_c          :                 -0.006715  Name: Fe2+ mitochondria                                             Charge:   2  Formula: Fe
fe3_c          :                 -0.007808  Name: Iron (Fe3+)                                                   Charge:   3  Formula: Fe
gln__L_c       :                  -0.26316  Name: L-Glutamine                                                   Charge:   0  Formula: C5H10N2O3
glu__L_c       :                  -0.26316  Name: L-Glutamate                                                   Charge:  -1  Formula: C5H8NO4
gly_c          :                 -0.612638  Name: Glycine                                                       Charge:   0  Formula: C2H5NO2
gtp_c          :                 -0.215096  Name: GTP C10H12N5O14P3                                             Charge:  -4  Formula: C10H12N5O14P3
h2o_c          :                     -29.0  Name: H2O H2O                                                       Charge:   0  Formula: H2O
his__L_c       :                 -0.094738  Name: L-Histidine                                                   Charge:   0  Formula: C6H9N3O2
ile__L_c       :                 -0.290529  Name: L-Isoleucine                                                  Charge:   0  Formula: C6H13NO2
k_c            :                 -0.195193  Name: Potassium                                                     Charge:   1  Formula: K
kdo2lipid4_p   :                 -0.019456  Name: KDO(2)-lipid IV(A)                                            Charge:  -6  Formula: C84H148N2O37P2
leu__L_c       :                 -0.450531  Name: L-Leucine                                                     Charge:   0  Formula: C6H13NO2
lys__L_c       :                 -0.343161  Name: L-Lysine                                                      Charge:   1  Formula: C6H15N2O2
met__L_c       :                 -0.153686  Name: L-Methionine                                                  Charge:   0  Formula: C5H11NO2S
mg2_c          :                 -0.008675  Name: Magnesium                                                     Charge:   2  Formula: Mg
mlthf_c        :                 -0.000223  Name: 5,10-Methylenetetrahydrofolate                                Charge:  -2  Formula: C20H21N7O6
mn2_c          :                 -0.000691  Name: Manganese                                                     Charge:   2  Formula: Mn
mql8_c         :                   -0.0001  Name: Menaquinol 8                                                  Charge:   0  Formula: C51H74O2
murein5px4p_p  :                 -0.013894  Name: Two disacharide linked murein units, pentapeptide crosslinked tetrapeptide (A2pm->D-ala) (middle of chain)  Charge:  -4  Formula: C77H117N15O40
nad_c          :                 -0.001831  Name: Nicotinamide adenine dinucleotide                             Charge:  -1  Formula: C21H26N7O14P2
nadp_c         :                 -0.000447  Name: Nicotinamide adenine dinucleotide phosphate                   Charge:  -3  Formula: C21H25N7O17P3
pe160_c        :                 -0.017868  Name: Phosphatidylethanolamine (dihexadecanoyl, n-C16:0)            Charge:   0  Formula: C37H74NO8P
pe160_p        :                 -0.045946  Name: Phosphatidylethanolamine (dihexadecanoyl, n-C16:0)            Charge:   0  Formula: C37H74NO8P
pe161_c        :                 -0.054154  Name: Phosphatidylethanolamine (dihexadec-9enoyl, n-C16:1)          Charge:   0  Formula: C37H70NO8P
pe161_p        :                  -0.02106  Name: Phosphatidylethanolamine (dihexadec-9enoyl, n-C16:1)          Charge:   0  Formula: C37H70NO8P
phe__L_c       :                 -0.185265  Name: L-Phenylalanine                                               Charge:   0  Formula: C9H11NO2
pheme_c        :                 -0.000223  Name: Protoheme C34H30FeN4O4                                        Charge:  -2  Formula: C34H30FeN4O4
pro__L_c       :                 -0.221055  Name: L-Proline                                                     Charge:   0  Formula: C5H9NO2
pydx5p_c       :                 -0.000223  Name: Pyridoxal 5'-phosphate                                        Charge:  -2  Formula: C8H8NO6P
ribflv_c       :                 -0.000223  Name: Riboflavin C17H20N4O6                                         Charge:   0  Formula: C17H20N4O6
ser__L_c       :                 -0.215792  Name: L-Serine                                                      Charge:   0  Formula: C3H7NO3
sheme_c        :                 -0.000223  Name: Siroheme C42H36FeN4O16                                        Charge:  -8  Formula: C42H36FeN4O16
so4_c          :                 -0.004338  Name: Sulfate                                                       Charge:  -2  Formula: O4S
thf_c          :                 -0.000223  Name: 5,6,7,8-Tetrahydrofolate                                      Charge:  -2  Formula: C19H21N7O6
thmpp_c        :                 -0.000223  Name: Thiamine diphosphate                                          Charge:  -2  Formula: C12H16N4O7P2S
thr__L_c       :                 -0.253687  Name: L-Threonine                                                   Charge:   0  Formula: C4H9NO3
trp__L_c       :                 -0.056843  Name: L-Tryptophan                                                  Charge:   0  Formula: C11H12N2O2
tyr__L_c       :                 -0.137896  Name: L-Tyrosine                                                    Charge:   0  Formula: C9H11NO3
utp_c          :                 -0.144104  Name: UTP C9H11N2O15P3                                              Charge:  -4  Formula: C9H11N2O15P3
val__L_c       :                 -0.423162  Name: L-Valine                                                      Charge:   0  Formula: C5H11NO2
zn2_c          :                 -0.000341  Name: Zinc                                                          Charge:   2  Formula: Zn
murein3px4p_p  :                 -0.000605  Name: Two disacharide linked murein units, tripeptide crosslinked tetrapeptide (A2pm->D-ala) (middle of chain)  Charge:  -4  Formula: C71H107N13O38
accoa_c        :                 -0.000279  Name: Acetyl-CoA                                                    Charge:  -4  Formula: C23H34N7O17P3S
murein4p3p_p   :                 -0.001345  Name: Two linked disacharide tetrapeptide and tripeptide murein units (uncrosslinked, middle of chain)  Charge:  -4  Formula: C71H109N13O39
5mthf_c        :                 -0.000223  Name: 5-Methyltetrahydrofolate                                      Charge:  -1  Formula: C20H24N7O6
nh4_c          :                 -0.012379  Name: Ammonium                                                      Charge:   1  Formula: H4N
chor_c         :                 -0.000223  Name: Chorismate                                                    Charge:  -2  Formula: C10H8O6
hemeO_c        :                 -0.000223  Name: Heme O C49H56FeN4O5                                           Charge:  -2  Formula: C49FeH56N4O5
murein4p4p_p   :                 -0.005381  Name: Two linked disacharide tetrapeptide murein units (uncrosslinked, middle of chain)  Charge:  -4  Formula: C74H114N14O40
2dmmql8_c      :                 -0.000223  Name: 2-Demethylmenaquinol 8                                        Charge:   0  Formula: C50H72O2
malcoa_c       :                  -3.1e-05  Name: Malonyl CoA C24H33N7O19P3S                                    Charge:  -5  Formula: C24H33N7O19P3S
murein4px4p_p  :                 -0.005448  Name: Two disacharide linked murein units, tetrapeptide corsslinked tetrapeptide (A2pm->D-ala) (middle of chain)  Charge:  -4  Formula: C74H112N14O39
ptrc_c         :                  -0.03327  Name: Putrescine                                                    Charge:   2  Formula: C4H14N2
nadph_c        :                 -0.000335  Name: Nicotinamide adenine dinucleotide phosphate - reduced         Charge:  -4  Formula: C21H26N7O17P3
mobd_c         :                    -7e-06  Name: Molybdate                                                     Charge:  -2  Formula: MoO4
nadh_c         :                  -4.5e-05  Name: Nicotinamide adenine dinucleotide - reduced                   Charge:  -2  Formula: C21H27N7O14P2
murein4px4px4p_p:                 -0.000673  Name: Three disacharide linked murein units (tetrapeptide crosslinked tetrapeptide (A2pm->D-ala) & tetrapeptide corsslinked tetrapeptide (A2pm->D-ala)) (middle of chain)  Charge:  -6  Formula: C111H167N21O58
succoa_c       :                  -9.8e-05  Name: Succinyl-CoA                                                  Charge:  -5  Formula: C25H35N7O19P3S
glc__D_c       :        -0.117366841601577  Name: D-Glucose                                                     Charge:   0  Formula: C6H12O6
rbflvrd_c      :     -5.42885385395863e-05  Name: Reduced riboflavin                                            Charge:   0  Formula: C17H22N4O6
nac_c          :     -0.000502314222072026  Name: Nicotinate                                                    Charge:  -1  Formula: C6H4NO2
pnto__R_c      :     -8.60937958309439e-05  Name: (R)-Pantothenate                                              Charge:  -1  Formula: C9H16NO5
clpn161_p      :                  -0.00229  Name: Cardiolipin (tetrahexadec-9-enoyl, n-C16:1)                   Charge:  -2  Formula: C73H132O17P2
pg160_p        :                 -0.010599  Name: Phosphatidylglycerol (dihexadecanoyl, n-C16:0)                Charge:  -1  Formula: C38H74O10P
clpn160_p      :                 -0.002944  Name: Cardiolipin (tetrahexadecanoyl, n-C16:0)                      Charge:  -2  Formula: C73H140O17P2
clpn181_p      :                  -0.00118  Name: Cardiolipin (tetraoctadec-11-enoyl, n-C18:1)                  Charge:  -2  Formula: C81H148O17P2
pe181_p        :                 -0.017704  Name: Phosphatidylethanolamine (dioctadec-11-enoyl, n-C18:1)        Charge:   0  Formula: C41H78NO8P
pg161_p        :                 -0.008244  Name: Phosphatidylglycerol (dihexadec-9-enoyl, n-C16:1)             Charge:  -1  Formula: C38H70O10P
ttdca_c        :     -0.000594246551765006  Name: Tetradecanoate (n-C14:0)                                      Charge:  -1  Formula: C14H27O2
hexadecacid_c  :                 -0.049935  Name: Hexadecanoic acid                                             Charge:   0  Formula: C16H32O2
hexedecacid_c  :                 -0.007033  Name: Hexadecenoic acid                                             Charge:   0  Formula: C16H30O2
octedecacid_c  :                 -0.131979  Name: Octadecenoic acid                                             Charge:   0  Formula: C18H34O2
octadecacid_c  :                 -0.007174  Name: Octadecanoic acid                                             Charge:   0  Formula: C18H36O2
fru_c          :                 -0.644556  Name: D-Fructose                                                    Charge:   0  Formula: C6H12O6
gal_c          :                 -0.005772  Name: D-Galactose                                                   Charge:   0  Formula: C6H12O6
xyl__D_c       :                 -0.005772  Name: D-Xylose                                                      Charge:   0  Formula: C5H10O5
man_c          :                  -0.00481  Name: D-Mannose                                                     Charge:   0  Formula: C6H12O6
arab__L_c      :                 -0.030016  Name: L-Arabinose                                                   Charge:   0  Formula: C5H10O5
thm_c          :                  -1.3e-05  Name: Thiamin                                                       Charge:   1  Formula: C12H17N4OS
lnlc_c         :                 -0.005903  Name: Linoleic acid (all cis C18:2) n-6                             Charge:  -1  Formula: C18H31O2
lnlncg_c       :                 -0.000364  Name: Gamma-linolenic acid                                          Charge:  -1  Formula: C18H29O2
adp_c          :                      29.0  Name: ADP C10H12N5O10P2                                             Charge:  -3  Formula: C10H12N5O10P2
h_c            :                      29.0  Name: H+                                                            Charge:   1  Formula: H
pi_c           :                      29.0  Name: Phosphate                                                     Charge:  -2  Formula: HO4P
ppi_c          :                  0.773903  Name: Diphosphate                                                   Charge:  -3  Formula: HO7P2

Sum charge: -0.10762534543035152

Associated Genes:

## Oxidative Phosphorylation complex addition

In [1]:
# we set an unlimited bound for the limiting substrate
reaction = model.reactions.get_by_id('EX_co2_e')
reaction.bounds = -100.0, 0.0

NameError: name 'model' is not defined

In [ ]:

reaction = model.reactions.get_by_id('EX_o2_e')
reaction.bounds = -6.92, 0.0

Addition of proton translocation to the NADH dehydrogenase reaction

In [ ]:
reaction = model.reactions.get_by_id('NADH5')
metabolite_to_add = 'h_p'
reaction.add_metabolites({metabolite_to_add: 4.0})

print(f"Reaction ID: {reaction.id}")
print(f"Name: {reaction.name}")
print(f"Equation: {reaction.reaction}")
print(f"Lower Bound: {reaction.lower_bound}")
print(f"Upper Bound: {reaction.upper_bound}")
print(reaction.annotation)
print(f"Genes: {[gene.id for gene in reaction.genes]}")

Reaction ID: NADH5
Name: NADH dehydrogenase (ubiquinone-8 )
Equation: 5.0 h_c + nadh_c + q8_c --> 4.0 h_p + nad_c + q8h2_c
Lower Bound: 0.0
Upper Bound: 1000.0
{'sbo': 'SBO:0000176', 'rhea': ['29107', '29108', '29109', '29110'], 'metanetx.reaction': 'MNXR101872', 'seed.reaction': 'rxn08975'}
Genes: ['AAFOLC_07640']

In [ ]:
summary = model.metabolites.get_by_id('h_p').summary()
summary

In [ ]:
model.slim_optimize()

0.024017630944258673

In [ ]:
model.summary()

# Setting the GAM value

In [18]:
GAM_metabolites_1 = {'atp_c': -150.5, 'h2o_c': -150.5}
GAM_metabolites_2 = {'adp_c': 150.5, 'pi_c': 150.5, 'h_c': 150.5}

# Get the biomass reaction
reaction = model.reactions.get_by_id('Growth')

# Update the coefficients for GAM_metabolites_1
for element, new_coefficient in GAM_metabolites_1.items():
    metabolite = model.metabolites.get_by_id(element)
    if metabolite in reaction.metabolites:
        print(f'Old coefficient for {element}: {reaction.metabolites[metabolite]}')
        reaction.add_metabolites({metabolite: new_coefficient - reaction.metabolites[metabolite]})
        print(f'Updated {element} coefficient to {new_coefficient}')

# Update the coefficients for GAM_metabolites_2
for element, new_coefficient in GAM_metabolites_2.items():
    metabolite = model.metabolites.get_by_id(element)
    if metabolite in reaction.metabolites:
        print(f'Old coefficient for {element}: {reaction.metabolites[metabolite]}')
        reaction.add_metabolites({metabolite: new_coefficient - reaction.metabolites[metabolite]})
        print(f'Updated {element} coefficient to {new_coefficient}')

# Optimize the model
solution = model.slim_optimize()
print(f'Optimal solution: {solution}')

Old coefficient for atp_c: -95.5
Updated atp_c coefficient to -150.5
Old coefficient for h2o_c: -95.5
Updated h2o_c coefficient to -150.5
Old coefficient for adp_c: 95.5
Updated adp_c coefficient to 150.5
Old coefficient for pi_c: 95.5
Updated pi_c coefficient to 150.5
Old coefficient for h_c: 95.5
Updated h_c coefficient to 150.5
Optimal solution: 0.05382834841324691

Set the NGAM value

In [ ]:
reaction = model.reactions.get_by_id('ATPM')
reaction.bounds = 9.27, 1000.0

In [1]:
sbml_filename = "C:\\Users\\adam-1y9pxi6q95ggpmx\\Documents\\PhD\\10-19 Research\\11 Data\\11.09 Models\\Manual_curation\\Energy_consumption\\241209_NGAM_coef_update_GAM.sbml"
cobra.io.write_sbml_model(model, sbml_filename)

NameError: name 'cobra' is not defined