In [1]:
import escher
from escher import Builder
from time import sleep
import cobra
import pandas as pd
from cobra.io import load_model
from cobra.io import load_json_model, save_json_model, load_matlab_model, save_matlab_model, read_sbml_model, write_sbml_model
from cobra import Model, Reaction, Metabolite, Gene
import numpy as np
import jupyter_utils as ju

In [3]:
escher.rc['never_ask_before_quit'] = True

In [4]:
builder = Builder()

In [9]:
#json_filename = "C:\\Users\\adam-1y9pxi6q95ggpmx\\Documents\\PhD\\10-19 Research\\11 Data\\11.09 Models\\Manual_curation\\Energy_consumption\\250308_hydrogenases_complete.json"
json_filename = "C:\\Users\\adam-1y9pxi6q95ggpmx\\Documents\\PhD\\10-19 Research\\11 Data\\11.09_Models\\250808_iABA974_BLG.json"

In [10]:
builder = Builder(
    model_json=json_filename
)

In [12]:
base_dir = Path.home() / "Documents" / "PhD" / "10-19 Research" / "11 Data" / "11.09_Models"
model = ju.load_model(base_dir,"Experiment", "250723_iABA974_BLG.sbml")

print reaction details

In [87]:
ju.print_reaction_details(model, 'PPCSCT')

Reaction ID   : PPCSCT
Name          : Propanoyl-CoA: succinate CoA-transferase
Equation      : ppcoa_c + succ_c --> ppa_c + succoa_c
Lower Bound   : 0.0
Upper Bound   : 1000.0

Metabolites and Stoichiometry:
 - ppcoa_c        :   -1.0  Name: Propanoyl-CoA                                      Charge:  -4  Formula: C24H36N7O17P3S
 - succ_c         :   -1.0  Name: Succinate                                          Charge:  -2  Formula: C4H4O4
 - ppa_c          :    1.0  Name: Propionate (n-C3:0)                                Charge:  -1  Formula: C3H5O2
 - succoa_c       :    1.0  Name: Succinyl-CoA                                       Charge:  -5  Formula: C25H35N7O19P3S

Sum of Charge Balance: 0.0

Associated Genes:
 - AAFOLC_22360

summary of metabolite

In [85]:
summary = model.metabolites.get_by_id('accoa_c').summary()

In [86]:
summary

In [43]:
search_word = 'glyc3p_c'
ju.search_metabolite_info(model,search_word)

🧪 Metabolite: glyc3p_c
 - Name       : Glycerol 3-phosphate
 - Formula    : C3H7O6P
 - Charge     : -2
 - Compartment: c
 - Annotations: {'sbo': 'SBO:0000247', 'reactome': ['R-ALL-188458', 'R-ALL-76114'], 'inchikey': 'AWUCVROLDVIAJX-GSVOUGTGSA-L', 'kegg.compound': 'C00093', 'chebi': ['CHEBI:10648', 'CHEBI:12843', 'CHEBI:12848', 'CHEBI:15978', 'CHEBI:26705', 'CHEBI:42793', 'CHEBI:57597'], 'hmdb': ['HMDB00126', 'HMDB02722', 'HMDB0000126'], 'biocyc': 'META:GLYCEROL-3P', 'metanetx.chemical': 'MNXM66', 'seed.compound': 'cpd00080', 'metacyc': 'GLYCEROL-3P', 'reactome.compound': ['R-ALL-76114', 'R-ALL-188458'], 'bigg.metabolite': 'glyc3p'}
 - Related Reactions: GLYC3Pabcpp, PGSA160, PGSA141, PGSA180, GLYK1, GLYC3Pabc, APG3PAT181, HDECH, G3PD1ir, G3PD6, PGSA120, G3PD2, GPDDA2, GPDDA4, PGSA161, APG3PAT160, G3PD5, G3PD4, PGSA140, GLYK, PGSA181
 - Associated Genes : AAFOLC_18795, AAFOLC_13060, AAFOLC_07550, AAFOLC_08115, AAFOLC_10475, AAFOLC_20350, AAFOLC_18785, AAFOLC_10485, AAFOLC_08110, AAFOLC_21865, AAFOLC_09250

Create reaction flux csv

In [13]:
reactions_data = pd.DataFrame(columns=['ID','time 0sec'])
solution = model.optimize()
# Iterate over all reactions in the model and populate the DataFrame
for reaction in model.reactions:
    # Create a DataFrame for the current reaction
    reaction_data = pd.DataFrame([{
        "ID": reaction.id,
        "time 0sec": solution.fluxes[reaction.id],}])
    
    # Concatenate the current reaction's DataFrame to the main DataFrame
    reactions_data = pd.concat([reactions_data, reaction_data], ignore_index=True)

# Print the resulting DataFrame to verify the results
reactions_data.to_csv('../Data/Escher_data/reactions_data_BLG.csv',index=False)

C:\Users\adam-1y9pxi6q95ggpmx\AppData\Local\Temp\ipykernel_20148\1036130611.py:11: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  reactions_data = pd.concat([reactions_data, reaction_data], ignore_index=True)

Builder

In [11]:
builder

Builder(never_ask_before_quit=True)