In [1]:
import escher
from escher import Builder
from time import sleep
import cobra
import pandas as pd
from cobra.io import load_model
from cobra.io import load_json_model, save_json_model, load_matlab_model, save_matlab_model, read_sbml_model, write_sbml_model
from cobra import Model, Reaction, Metabolite, Gene
import numpy as np

In [2]:
escher.rc['never_ask_before_quit'] = True

In [3]:
builder = Builder()

In [4]:
#json_filename = "C:\\Users\\adam-1y9pxi6q95ggpmx\\Documents\\PhD\\10-19 Research\\11 Data\\11.09 Models\\Manual_curation\\Energy_consumption\\250308_hydrogenases_complete.json"
json_filename = "C:\\Users\\adam-1y9pxi6q95ggpmx\\Documents\\PhD\\10-19 Research\\11 Data\\11.09 Models\\Manual_curation\\Energy_consumption\\250314_growth_glucose.json"

In [5]:
builder = Builder(
    model_json=json_filename
)

In [6]:
model = read_sbml_model('C:\\Users\\adam-1y9pxi6q95ggpmx\\Documents\\PhD\\10-19 Research\\11 Data\\11.09 Models\\Manual_curation\\Energy_consumption\\250314_growth_glucose.sbml')

In [29]:
summary = model.metabolites.get_by_id('coa_c').summary()

In [30]:
summary

In [7]:
reactions_data = pd.DataFrame(columns=['ID','time 0sec'])
solution = model.optimize()
# Iterate over all reactions in the model and populate the DataFrame
for reaction in model.reactions:
    # Create a DataFrame for the current reaction
    reaction_data = pd.DataFrame([{
        "ID": reaction.id,
        "time 0sec": solution.fluxes[reaction.id],}])
    
    # Concatenate the current reaction's DataFrame to the main DataFrame
    reactions_data = pd.concat([reactions_data, reaction_data], ignore_index=True)

# Print the resulting DataFrame to verify the results
reactions_data.to_csv('reactions_data.csv',index=False)

In [9]:
builder

Builder(never_ask_before_quit=True)