Here will be a jupyter notebook for the FV analysis.

In [2]:
from cobra.flux_analysis import flux_variability_analysis
import jupyter_utils as ju

In [4]:
base_dir = Path.home() / "Documents" / "PhD" / "10-19 Research" / "11 Data" / "11.09_Models"
model = ju.load_model(base_dir,"Experiment", "250723_iABA974_BLG.sbml")

#### Amino acid sequence analyzer

The **A, C, D, etc.** are the **one-letter codes** for the 20 standard amino acids in proteins.

Here’s the full table for reference for BLG:

| Code  | Amino Acid Name | 
| ----- | --------------- | 
| **A** | Alanine = 8.12%        | 
| **C** | Cysteine = 1.28%        |
| **D** | Aspartic acid = 4.70 %  |
| **E** | Glutamic acid = 5.56 %  |
| **F** | Phenylalanine = 3.42 %   |
| **G** | Glycine = 9.40 %         |
| **H** | Histidine = 2.99 %       |
| **I** | Isoleucine  = 2.14 %     |
| **K** | Lysine = 2.56 %          |
| **L** | Leucine = 15.81 %         |
| **M** | Methionine = 1.28 %      |
| **N** | Asparagine = 0.28 %     |
| **P** | Proline = 6.84 %         |
| **Q** | Glutamine = 6.41 %       |
| **R** | Arginine = 3.85 %        |
| **S** | Serine = 7.26 %          |
| **T** | Threonine = 4.70 %      |
| **V** | Valine = 7.69 %         |
| **W** | Tryptophan = 2.99 %      |
| **Y** | Tyrosine = 2.14 %       |

In [ ]:
from Bio.SeqUtils.ProtParam import ProteinAnalysis

# Example sequence
sequence = "MIPEFSKSLARTSGLAQVASQCWRMGTEKGHQLPGLSSLWGPAVKVLESGPLLLLILSLGLARAQETLEDVPVQPGFDAQKVEGRWLTVQLAASHAPLAAPDDPLRLALHSIWSRGEDVELVLFWTGEGVCQGLNVTVHPTGLLGQYQSAFKGGGTILLHFVSTDYSHLILYVRFQDDGEVTSLWALLARRMLEDPQWLGQYLAYVSKFHLQEGPVFNLDDQCPPPEASVGATP"

# Create a ProteinAnalysis object
analysis = ProteinAnalysis(sequence)

# Get amino acid counts
aa_counts = analysis.count_amino_acids()

# Convert counts to percentages
total = sum(aa_counts.values())
aa_percentages = {aa: (count / total) * 100 for aa, count in aa_counts.items()}

# Print
for aa, pct in aa_percentages.items():
    print(f"{aa}: {pct:.2f}%")

In [32]:
ju.print_reaction_details(model,'G3PD2')

Reaction ID   : G3PD2
Name          : Glycerol-3-phosphate dehydrogenase (NADP)
Equation      : glyc3p_c + nadp_c <=> dhap_c + h_c + nadph_c
Lower Bound   : -1000.0
Upper Bound   : 1000.0

Metabolites and Stoichiometry:
 - glyc3p_c       :   -1.0  Name: Glycerol 3-phosphate                               Charge:  -2  Formula: C3H7O6P
 - nadp_c         :   -1.0  Name: Nicotinamide adenine dinucleotide phosphate        Charge:  -3  Formula: C21H25N7O17P3
 - dhap_c         :    1.0  Name: Dihydroxyacetone phosphate                         Charge:  -2  Formula: C3H5O6P
 - h_c            :    1.0  Name: H+                                                 Charge:   1  Formula: H
 - nadph_c        :    1.0  Name: Nicotinamide adenine dinucleotide phosphate - reduced Charge:  -4  Formula: C21H26N7O17P3

Sum of Charge Balance: 0.0

Associated Genes:
 - AAFOLC_07550

In [40]:
metabolite_to_check = model.metabolites.get_by_id('ac_c')
summary = metabolite_to_check.summary()

In [41]:
summary

#### Run FVA

In [37]:
model.objective = "Growth"
model.reactions.get_by_id('EX_BLG_x1_e').bounds = 0.02, 1000.0
model.summary()
model.optimize()

In [42]:
model.reactions.get_by_id('EX_BLG_x1_e').bounds = 0.02, 1000.0
model.summary()

In [2]:
base_dir = Path.home() / "Documents" / "PhD" / "SoF1-GEM" / "Results" 
file_path = base_dir / "FVA_analysis"

In [27]:
from cobra.flux_analysis import flux_variability_analysis
# Perform FVA for all reactions
fva_results = flux_variability_analysis(model, fraction_of_optimum=0.9)

# Display the results as a DataFrame
fva_df = fva_results.reset_index()
fva_df.columns = ["Reaction", "Minimum Flux", "Maximum Flux"]

base_dir = Path.home() / "Documents" / "PhD" / "SoF1-GEM" / "Data" 
file_path = base_dir / "FVA_analysis" 
#fva_df.to_excel(file_path/'250707_fva_autotrophic.xlsx')
print(fva_df)

               Reaction  Minimum Flux  Maximum Flux
0         EX_25dkglcn_e          0.00          0.00
1           EX_2ameph_e          0.00          0.00
2       EX_2m35mdntha_e          0.00          0.00
3           EX_2pglyc_e          0.00          0.00
4           EX_34dhbz_e          0.00          0.00
...                 ...           ...           ...
2387             CYTHYD          0.00          0.02
2388             Growth          0.03          0.03
2389  BLG_x1_production          0.07          0.08
2390            BLG_x1t          0.07          0.08
2391        EX_BLG_x1_e          0.07          0.08

[2392 rows x 3 columns]

Run FVA for a specific reaction

In [35]:
fva_results = flux_variability_analysis(model,reaction_list=('GLUDxi'), fraction_of_optimum=0.9)
fva_df = fva_results.reset_index()
fva_df.columns = ["Reaction", "Minimum Flux", "Maximum Flux"]
print(fva_df)

  Reaction  Minimum Flux  Maximum Flux
0   GLUDxi      -1000.00        999.79

Analyze FVA results

In [28]:
base_dir = Path.home() / "Documents" / "PhD" / "SoF1-GEM" 
file_path = base_dir / "Results" / "FVA_analysis" 
# Load the FVA result Excel file
#fva_df = pd.read_excel(file_path/"250807_fva_BLG_autotrophic.xlsx")

# Optional: Display floats with 2 decimals
pd.options.display.float_format = "{:.2f}".format

# Add a flux span column
fva_df["span"] = fva_df["Maximum Flux"] - fva_df["Minimum Flux"]

# 1. Blocked reactions: both min and max = 0
blocked = fva_df[(fva_df["Minimum Flux"] == 0) & (fva_df["Maximum Flux"] == 0)]
num_blocked = len(blocked)

# 2. Essential reactions: min == max != 0
essential = fva_df[(fva_df["Minimum Flux"] == fva_df["Maximum Flux"]) & (fva_df["Minimum Flux"] != 0)]
num_essential = len(essential)

# 3. Flexible reactions: span > 0
flexible = fva_df[fva_df["span"] > 0]
num_flexible = len(flexible)

# 4. Highly variable reactions (span ≥ 100)
high_variability = fva_df[fva_df["span"] >= 100]
num_high_var = len(high_variability)

# 5. Top 10 most variable reactions
top_10_variable = fva_df.sort_values(by="span", ascending=False).head(10)

# Print summary
print("🔍 Summary of FVA Analysis")
print(f"Total reactions: {len(fva_df)}")
print(f"Blocked reactions: {num_blocked}")
print(f"Essential reactions (fixed flux): {num_essential}")
print(f"Flexible reactions (variable flux): {num_flexible}")
print(f"Highly variable (span ≥ 100): {num_high_var}")
print("\nTop 10 most variable reactions:")
print(top_10_variable[["Reaction", "Minimum Flux", "Maximum Flux", "span"]])

🔍 Summary of FVA Analysis
Total reactions: 2392
Blocked reactions: 892
Essential reactions (fixed flux): 0
Flexible reactions (variable flux): 1500
Highly variable (span ≥ 100): 300

Top 10 most variable reactions:
      Reaction  Minimum Flux  Maximum Flux    span
1327    HBCHLR      -1000.00       1000.00 2000.00
2033   RECOAH3      -1000.00       1000.00 2000.00
2025   RECOAH2      -1000.00       1000.00 2000.00
421    ACOAD4f      -1000.00       1000.00 2000.00
802      CYTK2      -1000.00       1000.00 2000.00
1291   HACD1_1      -1000.00       1000.00 2000.00
933     ECOAH2      -1000.00       1000.00 2000.00
932   ECOAH1_1      -1000.00       1000.00 2000.00
1293     HACD2      -1000.00       1000.00 2000.00
1309     HACD4      -1000.00       1000.00 2000.00

In [29]:
fva_df['span'] = fva_df['span'].apply(lambda x: round(x, 6))

In [30]:
fva_df_filtered = fva_df[
    (fva_df['Maximum Flux'] != 0) & #remove unnecessary reactions
    (fva_df['Minimum Flux'] != 0) &
    (fva_df['span'] > 0.1) & # reactions with very low flexibility
    (fva_df['span'] < 1000)
]
fva_df_filtered = fva_df_filtered.sort_values("span",ascending=False,ignore_index=True) # reorder by the span from the highest to the lowest
fva_df_filtered.to_excel(file_path/'250812_fva_filtered_BLG_pure.xlsx')

In [11]:
fva_df_filtered

       Reaction  Minimum Flux  Maximum Flux  span
0       r2465_1         -2.59         -0.00  2.59
1          NH3c         -0.68          0.66  1.34
2        ORNTAC         -0.65          0.67  1.31
3         ACOTA         -0.67          0.65  1.31
4         ORNTA         -0.67          0.65  1.31
..          ...           ...           ...   ...
141  CLPNS161pp          0.00          0.11  0.11
142       PYDXO         -0.11         -0.00  0.11
143   ACPPAT181          0.00          0.11  0.11
144    AGPAT181          0.00          0.11  0.11
145  APG3PAT181          0.00          0.11  0.11

[146 rows x 4 columns]

remove loop reactions

In [ ]:
loop_reactions = [model.reactions.FRD7, model.reactions.SUCDi]
flux_variability_analysis(model, reaction_list=loop_reactions, loopless=False)